Sese Framework: sese/archive/ArchiveReader.cpp File Reference
ArchiveReader.cpp File Reference
#include <sese/archive/ArchiveReader.h>
#include <sese/archive/ArchiveInputStream.h>
#include <sese/io/File.h>
#include <archive.h>
#include <archive_entry.h>
Macros
#define XX ((struct archive *) (this->archive))
Functions
SESE_ALWAYS_INLINE int open (struct archive *a, void *data)
SESE_ALWAYS_INLINE int64_t read (struct archive *a, void *data, const void **buffer)
SESE_ALWAYS_INLINE int close (struct archive *a, void *data)
Macro Definition Documentation
XX
#define XX ((struct archive *) (this->archive))
Referenced by sese::archive::ArchiveWriter::addDirectory(), sese::archive::ArchiveWriter::addFile(), sese::archive::ArchiveWriter::addStream(), sese::archive::ArchiveWriter::ArchiveWriter(), sese::archive::ArchiveWriter::begin(), sese::archive::ArchiveWriter::done(), sese::archive::ArchiveReader::extract(), sese::archive::Config::fromValue(), sese::archive::ArchiveReader::getError(), sese::archive::ArchiveWriter::getError(), sese::archive::ArchiveReader::getErrorString(), sese::archive::ArchiveWriter::getErrorString(), sese::text::DateTimeParser::parse(), sese::Bitset32::rightRotate11(), sese::Bitset32::rightRotate13(), sese::Bitset32::rightRotate17(), sese::Bitset32::rightRotate18(), sese::Bitset32::rightRotate19(), sese::Bitset32::rightRotate2(), sese::Bitset32::rightRotate22(), sese::Bitset32::rightRotate25(), sese::Bitset32::rightRotate6(), sese::Bitset32::rightRotate7(), sese::archive::ArchiveWriter::setFilterBZip2(), sese::archive::ArchiveWriter::setFilterGRZip(), sese::archive::ArchiveWriter::setFilterGZip(), sese::archive::ArchiveWriter::setFilterLRZip(), sese::archive::ArchiveWriter::setFilterLZ4(), sese::archive::ArchiveWriter::setFilterLZip(), sese::archive::ArchiveWriter::setFilterLzma(), sese::archive::ArchiveWriter::setFilterLzop(), sese::archive::ArchiveWriter::setFilterNone(), sese::archive::ArchiveWriter::setFilterXZ(), sese::archive::ArchiveWriter::setFilterZstd(), sese::archive::ArchiveWriter::setFormat7z(), sese::archive::ArchiveWriter::setFormatISO(), sese::archive::ArchiveWriter::setFormatTar(), sese::archive::ArchiveWriter::setFormatXar(), sese::archive::ArchiveWriter::setFormatZip(), sese::archive::ArchiveReader::setOptions(), sese::archive::ArchiveWriter::setOptions(), sese::archive::ArchiveReader::setPassword(), sese::archive::ArchiveWriter::setPassword(), sese::archive::Config::toValue(), sese::archive::ArchiveReader::~ArchiveReader(), and sese::archive::ArchiveWriter::~ArchiveWriter().
Function Documentation
close()
SESE_ALWAYS_INLINE int close (struct archive * a, void * data)
References a, and sese::archive::ArchiveReader::closeCallback().
Referenced by sese::archive::ArchiveWriter::begin(), sese::internal::service::http::HttpsConnectionExImpl::checkKeepalive(), sese::net::Socket::close(), sese::archive::ArchiveReader::extract(), sese::internal::service::http::HttpConnectionEx::handleRstStreamFrame(), sese::event::KqueueEventLoop::init(), sese::event::EpollEventLoop::~EpollEventLoop(), and sese::event::KqueueEventLoop::~KqueueEventLoop().
open()
SESE_ALWAYS_INLINE int open (struct archive * a, void * data)
References a, and sese::archive::ArchiveReader::openCallback().
Referenced by sese::archive::ArchiveWriter::begin(), sese::archive::ArchiveReader::extract(), and sese::plugin::Module::openEx().
read()
SESE_ALWAYS_INLINE int64_t read (struct archive * a, void * data, const void ** buffer)
References a, and sese::archive::ArchiveReader::readCallback().
Referenced by sese::Compressor::deflate(), sese::archive::ArchiveReader::extract(), sese::iocp::IOBufNode::getReadableSize(), sese::Compressor::getTotalOut(), sese::Decompressor::getTotalOut(), sese::Decompressor::inflate(), sese::service::TcpTransporter::onRead(), sese::io::AbstractFixedBuffer::peek(), sese::io::AbstractFixedBuffer::read(), sese::internal::service::http::HttpConnectionExImpl::readBlock(), sese::internal::service::http::HttpsConnectionExImpl::readBlock(), sese::Compressor::reset(), sese::Decompressor::reset(), and sese::io::AbstractFixedBuffer::trunc().