Sese Framework: sese/text/DateTimeFormatter.cpp File Reference
DateTimeFormatter.cpp File Reference
#include "sese/text/DateTimeFormatter.h"
#include "sese/util/DateTime.h"
#include "sese/text/StringBuilder.h"
#include "sese/io/InputBufferWrapper.h"
#include <cstring>
#include <ctime>
Functions
static int count (const char &ch, const char *str)
Function Documentation
count()
static int count (const char & ch, const char * str) static
Referenced by sese::db::impl::MariaDriverInstanceImpl::createStatement(), sese::db::impl::PostgresDriverInstanceImpl::createStatement(), sese::db::impl::SqliteDriverInstanceImpl::createStatement(), sese::Value::List::erase(), sese::db::impl::PostgresPreparedStatementImpl::executeQuery(), sese::db::impl::PostgresPreparedStatementImpl::executeUpdate(), sstr::SStringView::find(), findPos2(), sese::text::DateTimeFormatter::format(), sese::text::FormatParameterCounter(), sese::db::impl::MariaPreparedStatementImpl::freeBindStruct(), sese::Yaml::getLine(), sstr::LeftShiftElement(), sese::db::impl::MariaPreparedStatementImpl::MariaPreparedStatementImpl(), sese::db::impl::MariaStmtResultSet::MariaStmtResultSet(), sese::Yaml::parseArray(), sese::Yaml::parseObject(), sese::db::impl::PostgresPreparedStatementImpl::PostgresPreparedStatementImpl(), sese::Range< TYPE >::Range(), sese::io::RandomInputStream::read(), sstr::RightShiftElement(), sese::db::impl::MariaPreparedStatementImpl::setDateTime(), sese::db::impl::PostgresPreparedStatementImpl::setDateTime(), sese::db::impl::SqlitePreparedStatementImpl::setDateTime(), sese::db::impl::MariaPreparedStatementImpl::setDouble(), sese::db::impl::PostgresPreparedStatementImpl::setDouble(), sese::db::impl::SqlitePreparedStatementImpl::setDouble(), sese::db::impl::MariaPreparedStatementImpl::setFloat(), sese::db::impl::PostgresPreparedStatementImpl::setFloat(), sese::db::impl::SqlitePreparedStatementImpl::setFloat(), sese::db::impl::MariaPreparedStatementImpl::setInteger(), sese::db::impl::PostgresPreparedStatementImpl::setInteger(), sese::db::impl::SqlitePreparedStatementImpl::setInteger(), sese::db::impl::MariaPreparedStatementImpl::setLong(), sese::db::impl::PostgresPreparedStatementImpl::setLong(), sese::db::impl::SqlitePreparedStatementImpl::setLong(), sese::db::impl::MariaPreparedStatementImpl::setNull(), sese::db::impl::PostgresPreparedStatementImpl::setNull(), sese::db::impl::SqlitePreparedStatementImpl::setNull(), sese::db::impl::MariaPreparedStatementImpl::setText(), sese::db::impl::PostgresPreparedStatementImpl::setText(), sese::db::impl::SqlitePreparedStatementImpl::setText(), sese::db::impl::SqlitePreparedStatementImpl::SqlitePreparedStatementImpl(), sese::system::FileNotifier::Impl::start(), sese::Yaml::streamify(), sese::Json::streamifyArray(), sese::Yaml::streamifyArray(), sese::Json::streamifyObject(), sese::Yaml::streamifyObject(), sstr::SStringView::substring(), sstr::SStringView::toCWString(), sese::Version::toShortString(), sese::text::Number::toString(), sese::Value::toString(), sese::Value::toStringDict(), sese::Value::toStringList(), sese::system::Semaphore::Impl::tryLock(), sese::Value::writeSpace(), sese::Yaml::writeSpace(), and sese::db::impl::SqlitePreparedStatementImpl::~SqlitePreparedStatementImpl().