Sese Framework: sese::net::IPAddress Class Reference
sese::net::IPAddress Class Reference abstract
IP address class.
#include <IPAddress.h>
Public Types
using Ptr = std::shared_ptr<IPAddress>
Public Types inherited from sese::net::Address
using Ptr = std::shared_ptr<Address>
Public Member Functions
virtual Ptr getBroadcastAddress (uint32_t prefix_len) const noexcept=0
virtual Ptr getNetworkAddress (uint32_t prefix_len) const noexcept=0
virtual Ptr getSubnetMask (uint32_t prefix_len) const noexcept=0
virtual void setPort (uint16_t port) noexcept=0
virtual uint16_t getPort () const noexcept=0
virtual void setFamily (uint16_t family) noexcept=0
virtual uint16_t getFamily () noexcept=0
Public Member Functions inherited from sese::net::Address
virtual ~Address ()=default
virtual sockaddr * getRawAddress () const noexcept=0
virtual socklen_t getRawAddressLength () const noexcept=0
virtual std::string getAddress () const noexcept=0
Static Public Member Functions
static Ptr create (const char *address, uint16_t port=0)
Static Public Member Functions inherited from sese::net::Address
static Ptr create (const sockaddr *address, socklen_t address_len)
static bool lookUp (std::vector< Address::Ptr > &result, const std::string &host, int family=AF_INET, int type=0, int protocol=0)
static Address::Ptr lookUpAny (const std::string &host, int family=AF_INET, int type=0, int protocol=0)
Detailed Description
IP address class.
Member Typedef Documentation
Ptr
using sese::net::IPAddress::Ptr = std::shared_ptr<IPAddress>
Member Function Documentation
create()
IPAddress::Ptr IPAddress::create (const char * address, uint16_t port = 0) static
References sese::net::Address::create(), and setPort().
Referenced by sese::net::dns::Resolver::addNameServer().
getBroadcastAddress()
virtual Ptr sese::net::IPAddress::getBroadcastAddress (uint32_t prefix_len) const nodiscard pure virtual noexcept
Implemented in sese::net::IPv4Address, and sese::net::IPv6Address.
getFamily()
virtual uint16_t sese::net::IPAddress::getFamily () nodiscard pure virtual noexcept
Implemented in sese::net::IPv4Address, and sese::net::IPv6Address.
Referenced by sese::_windows::iocp::v1::NativeIOCPServer::init(), and sese::_windows::iocp::v1::NativeIOCPServer::postConnect().
getNetworkAddress()
virtual Ptr sese::net::IPAddress::getNetworkAddress (uint32_t prefix_len) const nodiscard pure virtual noexcept
Implemented in sese::net::IPv4Address, and sese::net::IPv6Address.
getPort()
virtual uint16_t sese::net::IPAddress::getPort () const nodiscard pure virtual noexcept
Implemented in sese::net::IPv4Address, and sese::net::IPv6Address.
getSubnetMask()
virtual Ptr sese::net::IPAddress::getSubnetMask (uint32_t prefix_len) const nodiscard pure virtual noexcept
Implemented in sese::net::IPv4Address, and sese::net::IPv6Address.
setFamily()
virtual void sese::net::IPAddress::setFamily (uint16_t family) pure virtual noexcept
Implemented in sese::net::IPv4Address, and sese::net::IPv6Address.
setPort()
virtual void sese::net::IPAddress::setPort (uint16_t port) pure virtual noexcept
Implemented in sese::net::IPv4Address, and sese::net::IPv6Address.
Referenced by create().
The documentation for this class was generated from the following files:
sese/net/IPAddress.h
sese/net/IPAddress.cpp