Sese Framework: sese::system::Process Class Reference
sese::system::Process Class Reference
Process Class.
#include <Process.h>
Public Types
using Ptr = std::unique_ptr<Process>
Public Member Functions
int wait () const noexcept
bool kill () const noexcept
pid_t getProcessId () const noexcept
virtual ~Process () noexcept=default
Static Public Member Functions
static Result< Process::Ptr, ErrorCode > createEx (const std::string &exec, const std::vector< std::string > &args={}) noexcept
static pid_t getCurrentProcessId () noexcept
Private Member Functions
Process ()=default
Private Attributes
pid_t id = -1
Detailed Description
Process Class.
Member Typedef Documentation
Ptr
using sese::system::Process::Ptr = std::unique_ptr<Process>
Constructor & Destructor Documentation
Process()
sese::system::Process::Process () private default
~Process()
Process::~Process () virtual default noexcept
Member Function Documentation
createEx()
sese::Result< Process::Ptr, sese::ErrorCode > Process::createEx (const std::string & exec, const std::vector< std::string > & args = {}) static noexcept
References sese::getErrorCode(), sese::getErrorString(), and MAKE_UNIQUE_PRIVATE.
Referenced by sese::system::ProcessBuilder::createEx().
getCurrentProcessId()
sese::pid_t Process::getCurrentProcessId () static nodiscard noexcept
Get the current process ID
Returns
Current process ID
getProcessId()
sese::pid_t Process::getProcessId () const nodiscard noexcept
Get the process ID
Returns
Process object ID
References id.
kill()
bool Process::kill () const nodiscard noexcept
Kill the process
Returns
Operation result
wait()
int Process::wait () const nodiscard noexcept
Wait for the process to end
Returns
Process exit code
Member Data Documentation
id
pid_t sese::system::Process::id = -1 private
Referenced by getProcessId().
The documentation for this class was generated from the following files:
sese/system/Process.h
sese/native/unix/system/Process.cpp
sese/native/win/system/Process.cpp