Sese Framework: sese::net::http::HPackUtil Class Reference
sese::net::http::HPackUtil Class Reference final
HPACK decompression tool class.
#include <HPackUtil.h>
Public Types
using InputStream = io::InputStream
using OutputStream = io::OutputStream
Public Member Functions
HPackUtil ()=delete
Public Member Functions inherited from sese::NotInstantiable
NotInstantiable ()=delete
virtual ~NotInstantiable ()=default
NotInstantiable (const NotInstantiable &)=delete
NotInstantiable & operator= (const NotInstantiable &)=delete
Static Public Member Functions
static uint32_t decode (InputStream *src, size_t content_length, DynamicTable &table, Header &header, bool is_resp, bool has_pseudo=true, uint32_t limit=8192) noexcept
static size_t encode (OutputStream *dest, DynamicTable &table, Header &once_header, Header &indexed_header) noexcept
Static Private Member Functions
static int decodeInteger (uint8_t &buf, InputStream *src, uint32_t &dest, uint8_t n) noexcept
static int decodeString (InputStream *src, std::string &dest) noexcept
static size_t encodeIndexCase0 (OutputStream *dest, size_t index) noexcept
static size_t encodeIndexCase1 (OutputStream *dest, size_t index) noexcept
static size_t encodeIndexCase2 (OutputStream *dest, size_t index) noexcept
static size_t encodeIndexCase3 (OutputStream *dest, size_t index) noexcept
static size_t encodeString (OutputStream *dest, const std::string &str) noexcept
static std::string buildCookieString (const Cookie::Ptr &cookie) noexcept
static bool setHeader (Header &header, const std::string &key, const std::string &value) noexcept
static bool verifyHeader (Header &header, bool is_resp) noexcept
Static Private Attributes
static const std::string REQ_PSEUDO_HEADER [4] {":method", ":scheme", ":authority", ":path"}
static HuffmanDecoder decoder {}
static HuffmanEncoder encoder {}
Detailed Description
HPACK decompression tool class.
Member Typedef Documentation
InputStream
using sese::net::http::HPackUtil::InputStream = io::InputStream
OutputStream
using sese::net::http::HPackUtil::OutputStream = io::OutputStream
Constructor & Destructor Documentation
HPackUtil()
sese::net::http::HPackUtil::HPackUtil () delete
Member Function Documentation
buildCookieString()
std::string HPackUtil::buildCookieString (const Cookie::Ptr & cookie) static private noexcept
References sese::text::DateTimeFormatter::format(), TIME_GREENWICH_MEAN_PATTERN, and sese::text::AbstractStringBuffer::toString().
decode()
uint32_t HPackUtil::decode (InputStream * src, size_t content_length, DynamicTable & table, Header & header, bool is_resp, bool has_pseudo = true, uint32_t limit = 8192) static noexcept
Attempt to parse HPACK compressed HEADERS from the stream
Parameters
src Stream source
content_length Length of content to be parsed
table Dynamic table used for parsing
header Storage for parsing results
is_resp Indicates if this is a response
has_pseudo Need to verify pseudo-fields at the beginning
limit Dynamic table size limit
Returns
Returns 0 if parsing is successful, otherwise returns an error code
Corresponds to case 0
Corresponding to case 1
Corresponding to the 2nd and 3rd cases
References sese::net::http::GOAWAY_COMPRESSION_ERROR, sese::net::http::GOAWAY_PROTOCOL_ERROR, sese::net::http::HttpUtil::parseFromCookie(), and sese::strcmpDoNotCase().
decodeInteger()
int HPackUtil::decodeInteger (uint8_t & buf, InputStream * src, uint32_t & dest, uint8_t n) static private noexcept
decodeString()
int HPackUtil::decodeString (InputStream * src, std::string & dest) static private noexcept
encode()
size_t HPackUtil::encode (OutputStream * dest, DynamicTable & table, Header & once_header, Header & indexed_header) static noexcept
Attempt to compress HEADERS in HPACK format
Parameters
dest Destination stream
table Dynamic table used for compression
once_header Non-indexed fields
indexed_header Indexed fields
Returns
Size of the buffer generated by compression
Corresponds to case 0
Corresponding to case 1
Add a dynamic table
Corresponds to case 0
Corresponding to case 1
Add a dynamic table
Add a dynamic table
Case 0
Case 2
Case 0
Case 2
Cookies are not compressed here
References sese::net::http::PREDEFINED_HEADERS.
encodeIndexCase0()
size_t HPackUtil::encodeIndexCase0 (OutputStream * dest, size_t index) static private noexcept
encodeIndexCase1()
size_t HPackUtil::encodeIndexCase1 (OutputStream * dest, size_t index) static private noexcept
encodeIndexCase2()
size_t HPackUtil::encodeIndexCase2 (OutputStream * dest, size_t index) static private noexcept
encodeIndexCase3()
size_t HPackUtil::encodeIndexCase3 (OutputStream * dest, size_t index) static private noexcept
encodeString()
size_t HPackUtil::encodeString (OutputStream * dest, const std::string & str) static private noexcept
Huffman compression is required
Huffman compression is not required
setHeader()
bool HPackUtil::setHeader (Header & header, const std::string & key, const std::string & value) static private noexcept
Check for duplicate pseudo-fields and set header values
See also
sese::net::http::HttpConverter
Parameters
header Target header
key Key
value Value
Returns
Whether setting was successful
verifyHeader()
bool HPackUtil::verifyHeader (Header & header, bool is_resp) static private noexcept
Validate pseudo-fields
Parameters
header Header
is_resp Whether it is a response
Returns
Validation result
Member Data Documentation
decoder
HuffmanDecoder HPackUtil::decoder {} static private
encoder
HuffmanEncoder HPackUtil::encoder {} static private
REQ_PSEUDO_HEADER
const std::string HPackUtil::REQ_PSEUDO_HEADER {":method", ":scheme", ":authority", ":path"} static private
The documentation for this class was generated from the following files:
sese/net/http/HPackUtil.h
sese/net/http/HPackUtil.cpp