Sese Framework: sese::security::evp::SHA512Context Class Reference
sese::security::evp::SHA512Context Class Reference
EVP SHA512 algorithm context.
#include <SHA512Context.h>
Public Member Functions
SHA512Context () noexcept
~SHA512Context () noexcept override
void update (const void *buffer, size_t len) noexcept override
void final () noexcept override
void * getResult () noexcept override
size_t getLength () noexcept override
Public Member Functions inherited from sese::security::evp::Context
Context ()=default
virtual ~Context () noexcept=default
Private Attributes
size_t length = 64
uint8_t result [64] {}
void * context = nullptr
Additional Inherited Members
Public Types inherited from sese::security::evp::Context
using Ptr = std::unique_ptr<Context>
Detailed Description
EVP SHA512 algorithm context.
Constructor & Destructor Documentation
SHA512Context()
sese::security::evp::SHA512Context::SHA512Context () noexcept
References context.
~SHA512Context()
sese::security::evp::SHA512Context::~SHA512Context () override noexcept
Member Function Documentation
final()
void sese::security::evp::SHA512Context::final () override virtual noexcept
Implements sese::security::evp::Context.
Referenced by sese::security::MessageDigest::digestSHA512().
getLength()
size_t sese::security::evp::SHA512Context::getLength () override virtual noexcept
Implements sese::security::evp::Context.
Referenced by sese::security::MessageDigest::digestSHA512().
getResult()
void * sese::security::evp::SHA512Context::getResult () override virtual noexcept
Implements sese::security::evp::Context.
Referenced by sese::security::MessageDigest::digestSHA512().
update()
void sese::security::evp::SHA512Context::update (const void * buffer, size_t len) override virtual noexcept
Implements sese::security::evp::Context.
Referenced by sese::security::MessageDigest::digestSHA512().
Member Data Documentation
context
void* sese::security::evp::SHA512Context::context = nullptr private
Referenced by SHA512Context().
length
size_t sese::security::evp::SHA512Context::length = 64 private
result
uint8_t sese::security::evp::SHA512Context::result[64] {} private
The documentation for this class was generated from the following files:
sese/security/evp/SHA512Context.h
sese/native/unix/security/evp/SHA512Context.cpp
sese/native/win/security/evp/SHA512Context.cpp