Sese Framework: sese::security::MessageDigest Class Reference
sese::security::MessageDigest Class Reference final
Message digest interface based on OPENSSL::CRYPTO.
#include <MessageDigest.h>
Public Types
enum class Type {
MD5 , SHA1 , SHA256 , SHA384 ,
SHA512 , SM3
}
using InputStream = io::InputStream
Public Member Functions
MessageDigest ()=delete
Public Member Functions inherited from sese::NotInstantiable
NotInstantiable ()=delete
virtual ~NotInstantiable ()=default
NotInstantiable (const NotInstantiable &)=delete
NotInstantiable & operator= (const NotInstantiable &)=delete
Static Public Member Functions
static std::string digest (Type type, InputStream *input, bool is_cap=false) noexcept
Static Private Member Functions
static void digestMD5 (char *str, InputStream *input, bool is_cap) noexcept
static void digestSH1 (char *str, InputStream *input, bool is_cap) noexcept
static void digestSHA256 (char *str, InputStream *input, bool is_cap) noexcept
static void digestSHA384 (char *str, InputStream *input, bool is_cap) noexcept
static void digestSHA512 (char *str, InputStream *input, bool is_cap) noexcept
static void digestSM3 (char *str, InputStream *input, bool is_cap) noexcept
Detailed Description
Message digest interface based on OPENSSL::CRYPTO.
Member Typedef Documentation
InputStream
using sese::security::MessageDigest::InputStream = io::InputStream
Member Enumeration Documentation
Type
enum class sese::security::MessageDigest::Type strong
Enumerator
MD5
SHA1
SHA256
SHA384
SHA512
SM3
Constructor & Destructor Documentation
MessageDigest()
sese::security::MessageDigest::MessageDigest () delete
Member Function Documentation
digest()
std::string sese::security::MessageDigest::digest (Type type, InputStream * input, bool is_cap = false) static noexcept
digestMD5()
void sese::security::MessageDigest::digestMD5 (char * str, InputStream * input, bool is_cap) static private noexcept
References sese::security::evp::MD5Context::final(), sese::security::evp::MD5Context::getLength(), sese::security::evp::MD5Context::getResult(), and sese::security::evp::MD5Context::update().
digestSH1()
void sese::security::MessageDigest::digestSH1 (char * str, InputStream * input, bool is_cap) static private noexcept
References sese::security::evp::SHA1Context::final(), sese::security::evp::SHA1Context::getLength(), sese::security::evp::SHA1Context::getResult(), and sese::security::evp::SHA1Context::update().
digestSHA256()
void sese::security::MessageDigest::digestSHA256 (char * str, InputStream * input, bool is_cap) static private noexcept
References sese::security::evp::SHA256Context::final(), sese::security::evp::SHA256Context::getLength(), sese::security::evp::SHA256Context::getResult(), and sese::security::evp::SHA256Context::update().
digestSHA384()
void sese::security::MessageDigest::digestSHA384 (char * str, InputStream * input, bool is_cap) static private noexcept
References sese::security::evp::SHA384Context::final(), sese::security::evp::SHA384Context::getLength(), sese::security::evp::SHA384Context::getResult(), and sese::security::evp::SHA384Context::update().
digestSHA512()
void sese::security::MessageDigest::digestSHA512 (char * str, InputStream * input, bool is_cap) static private noexcept
References sese::security::evp::SHA512Context::final(), sese::security::evp::SHA512Context::getLength(), sese::security::evp::SHA512Context::getResult(), and sese::security::evp::SHA512Context::update().
digestSM3()
void sese::security::MessageDigest::digestSM3 (char * str, InputStream * input, bool is_cap) static private noexcept
References sese::security::evp::SM3Context::final(), sese::security::evp::SM3Context::getLength(), sese::security::evp::SM3Context::getResult(), and sese::security::evp::SM3Context::update().
The documentation for this class was generated from the following files:
sese/security/MessageDigest.h
sese/security/MessageDigest.cpp