Sese Framework: sese::net::http::HttpClient::Impl Class Reference
sese::net::http::HttpClient::Impl Class Reference
HTTP/1.1 client based on ASIO.
Public Member Functions
Impl (const IPAddress::Ptr &addr, Request::Ptr req)
~Impl () override
bool request ()
void reset ()
Reset body-related settings.
virtual bool handshake ()
virtual bool shutdown ()
bool writeHeader (io::ByteBuilder &builder)
bool writeBodyByCallback ()
bool writeBodyByData ()
bool writeBodyByAuto ()
bool readBodyByCallback (size_t expect)
bool readBodyByData (size_t expect)
int64_t read (void *buf, size_t len) override
int64_t write (const void *buf, size_t len) override
int getLastError () const
std::string getLastErrorString () const
Public Member Functions inherited from sese::io::InputStream
virtual ~InputStream () noexcept=default
Public Member Functions inherited from sese::io::OutputStream
virtual ~OutputStream () noexcept=default
int64_t write (const std::string_view &buffer)
int64_t write (const text::StringView &buffer)
template<typename T >
int64_t write (std::vector< T > &buffer)
template<typename T , size_t N>
int64_t write (std::array< T, N > &buffer)
Public Attributes
IPAddress::Ptr address
CookieMap::Ptr cookies
asio::error_code code {}
asio::io_context ioContext
asio::ip::tcp::socket socket
bool first = true
Request::Ptr req = nullptr
Response::Ptr resp = nullptr
size_t expect_total = 0
io::PeekableStream * read_data = nullptr
OutputStream * write_data = nullptr
WriteCallback write_callback
ReadCallback read_callback
Additional Inherited Members
Public Types inherited from sese::io::InputStream
typedef std::shared_ptr< InputStream > Ptr
Public Types inherited from sese::io::OutputStream
typedef std::shared_ptr< OutputStream > Ptr
Detailed Description
HTTP/1.1 client based on ASIO.
Constructor & Destructor Documentation
Impl()
sese::net::http::HttpClient::Impl::Impl (const IPAddress::Ptr & addr, Request::Ptr req) inline
References address, cookies, req, reset(), and resp.
~Impl()
sese::net::http::HttpClient::Impl::~Impl () inline override
References socket.
Member Function Documentation
getLastError()
int sese::net::http::HttpClient::Impl::getLastError () const inline
References code.
getLastErrorString()
std::string sese::net::http::HttpClient::Impl::getLastErrorString () const inline
References code.
handshake()
virtual bool sese::net::http::HttpClient::Impl::handshake () inline virtual
Reimplemented in sese::net::http::HttpClient::SSLImpl.
Referenced by request().
read()
int64_t sese::net::http::HttpClient::Impl::read (void * buf, size_t len) inline override virtual
Implements sese::io::InputStream.
Reimplemented in sese::net::http::HttpClient::SSLImpl.
References code, read(), and socket.
Referenced by read(), readBodyByCallback(), and readBodyByData().
readBodyByCallback()
bool sese::net::http::HttpClient::Impl::readBodyByCallback (size_t expect) inline
References MTU_VALUE, read(), and write_callback.
Referenced by request().
readBodyByData()
bool sese::net::http::HttpClient::Impl::readBodyByData (size_t expect) inline
References MTU_VALUE, read(), and write_data.
Referenced by request().
request()
bool sese::net::http::HttpClient::Impl::request () inline
References address, code, sese::internal::net::convert(), expect_total, first, handshake(), sese::net::http::HEAD, read_callback, readBodyByCallback(), readBodyByData(), sese::net::http::HttpUtil::recvResponse(), req, reset(), resp, sese::net::http::HttpUtil::sendRequest(), shutdown(), socket, sese::strcmpDoNotCase(), write_callback, writeBodyByAuto(), writeBodyByCallback(), writeBodyByData(), and writeHeader().
reset()
void sese::net::http::HttpClient::Impl::reset () inline
Reset body-related settings.
References expect_total, read_callback, read_data, req, resp, write_callback, and write_data.
Referenced by Impl(), and request().
shutdown()
virtual bool sese::net::http::HttpClient::Impl::shutdown () inline virtual
Reimplemented in sese::net::http::HttpClient::SSLImpl.
Referenced by request().
write()
int64_t sese::net::http::HttpClient::Impl::write (const void * buf, size_t len) inline override virtual
Implements sese::io::OutputStream.
Reimplemented in sese::net::http::HttpClient::SSLImpl.
References code, and socket.
Referenced by writeBodyByAuto(), writeBodyByCallback(), writeBodyByData(), and writeHeader().
writeBodyByAuto()
bool sese::net::http::HttpClient::Impl::writeBodyByAuto () inline
References MTU_VALUE, req, and write().
Referenced by request().
writeBodyByCallback()
bool sese::net::http::HttpClient::Impl::writeBodyByCallback () inline
References expect_total, MTU_VALUE, read_callback, and write().
Referenced by request().
writeBodyByData()
bool sese::net::http::HttpClient::Impl::writeBodyByData () inline
References expect_total, MTU_VALUE, sese::io::PeekableStream::peek(), read_data, sese::io::PeekableStream::trunc(), and write().
Referenced by request().
writeHeader()
bool sese::net::http::HttpClient::Impl::writeHeader (io::ByteBuilder & builder) inline
References MTU_VALUE, sese::io::AbstractByteBuffer::peek(), sese::io::AbstractByteBuffer::resetPos(), sese::io::AbstractByteBuffer::trunc(), and write().
Referenced by request().
Member Data Documentation
address
IPAddress::Ptr sese::net::http::HttpClient::Impl::address
Referenced by Impl(), and request().
code
asio::error_code sese::net::http::HttpClient::Impl::code {}
Referenced by getLastError(), getLastErrorString(), sese::net::http::HttpClient::SSLImpl::handshake(), read(), sese::net::http::HttpClient::SSLImpl::read(), request(), sese::net::http::HttpClient::SSLImpl::shutdown(), write(), and sese::net::http::HttpClient::SSLImpl::write().
cookies
CookieMap::Ptr sese::net::http::HttpClient::Impl::cookies
Referenced by Impl().
expect_total
size_t sese::net::http::HttpClient::Impl::expect_total = 0
Referenced by request(), reset(), writeBodyByCallback(), and writeBodyByData().
first
bool sese::net::http::HttpClient::Impl::first = true
Referenced by request().
ioContext
asio::io_context sese::net::http::HttpClient::Impl::ioContext
read_callback
ReadCallback sese::net::http::HttpClient::Impl::read_callback
Referenced by request(), reset(), and writeBodyByCallback().
read_data
io::PeekableStream* sese::net::http::HttpClient::Impl::read_data = nullptr
Referenced by reset(), and writeBodyByData().
req
Request::Ptr sese::net::http::HttpClient::Impl::req = nullptr
Referenced by Impl(), request(), reset(), and writeBodyByAuto().
resp
Response::Ptr sese::net::http::HttpClient::Impl::resp = nullptr
Referenced by Impl(), request(), and reset().
socket
asio::ip::tcp::socket sese::net::http::HttpClient::Impl::socket
Referenced by read(), request(), write(), and ~Impl().
write_callback
WriteCallback sese::net::http::HttpClient::Impl::write_callback
Referenced by readBodyByCallback(), request(), and reset().
write_data
OutputStream* sese::net::http::HttpClient::Impl::write_data = nullptr
Referenced by readBodyByData(), and reset().
The documentation for this class was generated from the following file:
sese/internal/net/http/HttpClientImpl.cpp