Sese Framework: sese::net::ws::WebsocketAuthenticator Class Reference
sese::net::ws::WebsocketAuthenticator Class Reference final
Websocket Authenticator.
#include <WebsocketAuthenticator.h>
Public Member Functions
WebsocketAuthenticator ()=delete
Public Member Functions inherited from sese::NotInstantiable
NotInstantiable ()=delete
virtual ~NotInstantiable ()=default
NotInstantiable (const NotInstantiable &)=delete
NotInstantiable & operator= (const NotInstantiable &)=delete
Static Public Member Functions
static std::pair< std::unique_ptr< char[]>, std::unique_ptr< char[]> > generateKeyPair () noexcept
static bool verify (const char *key, const char *result) noexcept
static std::unique_ptr< char[]> toResult (const char *key) noexcept
Static Private Member Functions
static void generateKey (uint8_t key[16])
Generate a binary key.
Static Private Attributes
static const char * append_string = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
Detailed Description
Websocket Authenticator.
Constructor & Destructor Documentation
WebsocketAuthenticator()
sese::net::ws::WebsocketAuthenticator::WebsocketAuthenticator () delete
Member Function Documentation
generateKey()
void sese::net::ws::WebsocketAuthenticator::generateKey (uint8_t key[16]) static private
Generate a binary key.
generateKeyPair()
std::pair< std::unique_ptr< char[]>, std::unique_ptr< char[]> > sese::net::ws::WebsocketAuthenticator::generateKeyPair () static noexcept
Generate key pair
Returns
Key pair
References sese::Base64Converter::encode(), sese::SHA1Util::encode(), and in().
toResult()
std::unique_ptr< char[]> sese::net::ws::WebsocketAuthenticator::toResult (const char * key) static noexcept
Generate result from key
Parameters
key Key
Returns
Result
References sese::Base64Converter::encode(), sese::SHA1Util::encode(), and in().
verify()
bool sese::net::ws::WebsocketAuthenticator::verify (const char * key, const char * result) static noexcept
Validate key pair
Parameters
key Key
result Result
Returns
Validation result
References sese::Base64Converter::encode(), sese::SHA1Util::encode(), in(), and sese::strcmp().
Member Data Documentation
append_string
const char * sese::net::ws::WebsocketAuthenticator::append_string = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11" static private
The documentation for this class was generated from the following files:
sese/net/ws/WebsocketAuthenticator.h
sese/net/ws/WebSocketAuthenticator.cpp