Sese Framework: sese::Range< TYPE > Class Template Reference
sese::Range< TYPE > Class Template Reference
Range class.
#include <Range.h>
Classes
class Iterator
Iterators.
class ReverseIterator
Reverse Iterator.
Public Member Functions
Range (TYPE count)
Range (TYPE begin, TYPE end)
Iterator begin ()
Iterator end ()
ReverseIterator rbegin ()
ReverseIterator rend ()
bool exist (const TYPE &num) const
Private Attributes
TYPE beginNumber = 0
TYPE endNumber = 0
Detailed Description
template<class TYPE>
class sese::Range< TYPE >
Range class.
Template Parameters
TYPE Value type
Constructor & Destructor Documentation
Range() [1/2]
template<class TYPE > sese::Range< TYPE >::Range (TYPE count) inline explicit
This constructor is only for positive and incrementing ranges
Parameters
count The size of the range
Note
[1, count]
References sese::Range< TYPE >::beginNumber, count(), and sese::Range< TYPE >::endNumber.
Range() [2/2]
template<class TYPE > sese::Range< TYPE >::Range (TYPE begin, TYPE end) inline
This constructor is for any range, regardless of whether it is incrementing or decrementing
Parameters
begin Start
end End
Note
[begin, end]
References sese::Range< TYPE >::begin(), sese::Range< TYPE >::beginNumber, sese::Range< TYPE >::end(), and sese::Range< TYPE >::endNumber.
Member Function Documentation
begin()
template<class TYPE > Iterator sese::Range< TYPE >::begin () inline
References sese::Range< TYPE >::beginNumber.
Referenced by sese::Range< TYPE >::Range().
end()
template<class TYPE > Iterator sese::Range< TYPE >::end () inline
References sese::Range< TYPE >::endNumber.
Referenced by sese::Range< TYPE >::Range().
exist()
template<class TYPE > bool sese::Range< TYPE >::exist (const TYPE & num) const inline
Check if a value is within the range
Parameters
num The value to check
Returns
The result
References sese::Range< TYPE >::beginNumber, and sese::Range< TYPE >::endNumber.
rbegin()
template<class TYPE > ReverseIterator sese::Range< TYPE >::rbegin () inline
References sese::Range< TYPE >::endNumber.
Referenced by sese::TimeWheel::TimeWheel().
rend()
template<class TYPE > ReverseIterator sese::Range< TYPE >::rend () inline
References sese::Range< TYPE >::beginNumber.
Referenced by sese::TimeWheel::TimeWheel().
Member Data Documentation
beginNumber
template<class TYPE > TYPE sese::Range< TYPE >::beginNumber = 0 private
Referenced by sese::Range< TYPE >::begin(), sese::Range< TYPE >::exist(), sese::Range< TYPE >::Range(), sese::Range< TYPE >::Range(), and sese::Range< TYPE >::rend().
endNumber
template<class TYPE > TYPE sese::Range< TYPE >::endNumber = 0 private
Referenced by sese::Range< TYPE >::end(), sese::Range< TYPE >::exist(), sese::Range< TYPE >::Range(), sese::Range< TYPE >::Range(), and sese::Range< TYPE >::rbegin().
The documentation for this class was generated from the following file:
sese/util/Range.h