Sese Framework: sese::net::http::Request Class Reference
sese::net::http::Request Class Reference final
HTTP Request Class.
#include <Request.h>
Public Types
using Ptr = std::unique_ptr<Request>
Public Types inherited from sese::net::http::RequestHeader
using Ptr = std::unique_ptr<RequestHeader>
Public Types inherited from sese::net::http::Header
using Ptr = std::unique_ptr<Header>
using KeyValueType = std::pair<std::string, std::string>
Public Member Functions
io::ByteBuilder & getBody ()
void swap (Request &another) noexcept
Public Member Functions inherited from sese::net::http::RequestHeader
RequestHeader ()=default
RequestHeader (const std::initializer_list< KeyValueType > &initializer_list)
RequestType getType () const
void setType (RequestType request_type)
const std::string & getUri () const
void setUri (const std::string &uri)
const std::string & getQueryArg (const std::string &key, const std::string &default_value) const
void setQueryArg (const std::string &key, const std::string &value)
size_t queryArgsSize () const
bool queryArgsEmpty () const
void queryArgsClear ()
bool queryArgsExist (const std::string &key)
const std::string & getQueryArg (const std::string &key)
HttpVersion getVersion () const
void setVersion (HttpVersion new_version)
std::string getUrl () const
void setUrl (const std::string &request_url)
Public Member Functions inherited from sese::net::http::Header
Header ()=default
Header (const std::initializer_list< KeyValueType > &initializer_list) noexcept
virtual ~Header ()=default
void set (const std::string &key, const std::string &value) noexcept
const std::string & get (const std::string &key, const std::string &default_value) noexcept
std::map< std::string, std::string >::iterator begin () noexcept
std::map< std::string, std::string >::iterator end () noexcept
auto find (const std::string &key) noexcept
void clear ()
bool empty () const
size_t size () const
bool exist (const std::string &key)
const std::string & get (const std::string &key)
const CookieMap::Ptr & getCookies () const
void setCookies (const CookieMap::Ptr &cookies)
Cookie::Ptr getCookie (const std::string &name) const
void setCookie (const Cookie::Ptr &cookie)
Private Attributes
io::ByteBuilder body {8192}
Additional Inherited Members
Protected Attributes inherited from sese::net::http::RequestHeader
RequestType type = RequestType::GET
std::string uri = "/"
HttpVersion version = HttpVersion::VERSION_1_1
std::map< std::string, std::string > query_args
Protected Attributes inherited from sese::net::http::Header
StrCaseMap< std::string > headers
CookieMap::Ptr cookies = nullptr
Detailed Description
HTTP Request Class.
Member Typedef Documentation
Ptr
using sese::net::http::Request::Ptr = std::unique_ptr<Request>
Member Function Documentation
getBody()
io::ByteBuilder & sese::net::http::Request::getBody () inline
References body.
Referenced by sese::net::http::HttpServletContext::getInputStream(), sese::internal::net::http::HttpClientImpl::request(), and sese::internal::net::http::HttpClientImpl::writeBodyByAuto().
swap()
void sese::net::http::Request::swap (Request & another) noexcept
Member Data Documentation
body
io::ByteBuilder sese::net::http::Request::body {8192} private
Referenced by getBody().
The documentation for this class was generated from the following files:
sese/net/http/Request.h
sese/net/http/Request.cpp