Sese Framework: sese::_windows::iocp::v1::NativeIOCPServer Class Reference
sese::_windows::iocp::v1::NativeIOCPServer Class Reference
Native IOCP Server for Windows.
#include <NativeIOCPServer_V1.h>
Public Types
using Context = NativeContext
using DeleteContextCallback = std::function<void(Context *data)>
Public Member Functions
virtual ~NativeIOCPServer ()=default
bool init ()
void shutdown ()
void postRead (Context *ctx)
void postWrite (Context *ctx)
void postClose (Context *ctx)
void postConnect (const net::IPAddress::Ptr &to, const security::SSLContext::Ptr &cli_ctx, void *data=nullptr)
void setTimeout (Context *ctx, int64_t seconds)
void cancelTimeout (Context *ctx)
virtual void onAcceptCompleted (Context *ctx)
virtual void onPreRead (Context *ctx)
virtual void onReadCompleted (Context *ctx)
virtual void onWriteCompleted (Context *ctx)
virtual void onTimeout (Context *ctx)
virtual void onPreConnect (Context *ctx)
virtual void onConnected (Context *ctx)
virtual void onAlpnGet (Context *ctx, const uint8_t *in, uint32_t in_length)
int onAlpnSelect (const uint8_t **out, uint8_t *out_length, const uint8_t *in, uint32_t in_length)
void setAddress (const net::IPAddress::Ptr &addr)
void setThreads (size_t number_of_threads)
void setServCtx (const security::SSLContext::Ptr &ctx)
void setServProtos (const std::string &protos)
void setClientProtos (const std::string &protos)
void setDeleteContextCallback (const DeleteContextCallback &callback)
const security::SSLContext::Ptr & getServCtx () const
const DeleteContextCallback & getDeleteContextCallback () const
bool isActiveReleaseMode () const
Static Public Member Functions
static void onDeleteContext (Context *)
Protected Member Functions
void setActiveReleaseMode (bool enable)
void releaseContext (Context *ctx)
void acceptThreadProc ()
void eventThreadProc ()
bool initConnectEx ()
Static Protected Member Functions
static int alpnCallbackFunction (void *ssl, const uint8_t **out, uint8_t *out_length, const uint8_t *in, uint32_t in_length, NativeIOCPServer *server)
static long bioCtrl (void *bio, int cmd, long num, void *ptr)
static int bioWrite (void *bio, const char *in, int length)
static int bioRead (void *bio, char *out, int length)
Protected Attributes
void * connectEx {}
std::atomic_bool isShutdown {false}
HANDLE iocpFd {INVALID_HANDLE_VALUE}
SOCKET listenFd {INVALID_SOCKET}
net::IPAddress::Ptr address {}
Thread::Ptr acceptThread {}
TimeWheel wheel {}
std::set< OverlappedWrapper * > wrapperSet {}
std::mutex wrapperSetMutex {}
size_t threads {2}
std::vector< Thread::Ptr > eventThreadGroup {}
DeleteContextCallback deleteContextCallback = onDeleteContext
security::SSLContext::Ptr sslCtx {}
void * bioMethod {}
std::string servProtos {}
std::string clientProtos {}
Private Attributes
bool activeReleaseMode = true
Detailed Description
Native IOCP Server for Windows.
Member Typedef Documentation
Context
using sese::_windows::iocp::v1::NativeIOCPServer::Context = NativeContext
DeleteContextCallback
using sese::_windows::iocp::v1::NativeIOCPServer::DeleteContextCallback = std::function<void(Context *data)>
Constructor & Destructor Documentation
~NativeIOCPServer()
virtual sese::_windows::iocp::v1::NativeIOCPServer::~NativeIOCPServer () virtual default
Member Function Documentation
acceptThreadProc()
void NativeIOCPServer::acceptThreadProc () protected
References bioMethod, sese::TimeWheel::check(), sese::net::Socket::close(), sese::_windows::iocp::v1::OverlappedWrapper::ctx, sese::_windows::iocp::v1::NativeContext::fd, iocpFd, isShutdown, listenFd, onAcceptCompleted(), onAlpnGet(), sese::net::Socket::setNonblocking(), sslCtx, wheel, wrapperSet, and wrapperSetMutex.
Referenced by init().
alpnCallbackFunction()
int NativeIOCPServer::alpnCallbackFunction (void * ssl, const uint8_t ** out, uint8_t * out_length, const uint8_t * in, uint32_t in_length, NativeIOCPServer * server) static protected
References in(), and onAlpnSelect().
Referenced by init().
bioCtrl()
long NativeIOCPServer::bioCtrl (void * bio, int cmd, long num, void * ptr) static protected
Referenced by init().
bioRead()
int NativeIOCPServer::bioRead (void * bio, char * out, int length) static protected
Referenced by init().
bioWrite()
int NativeIOCPServer::bioWrite (void * bio, const char * in, int length) static protected
References in().
Referenced by init().
cancelTimeout()
void NativeIOCPServer::cancelTimeout (NativeIOCPServer::Context * ctx)
Cancel a timeout event
Parameters
ctx The operation context
References sese::TimeWheel::cancel(), sese::_windows::iocp::v1::NativeContext::timeoutEvent, wheel, and wrapperSetMutex.
eventThreadProc()
void NativeIOCPServer::eventThreadProc () protected
References activeReleaseMode, bioMethod, sese::_windows::iocp::v1::NativeContext::CLOSE, sese::_windows::iocp::v1::NativeContext::CONNECT, e, sese::net::getNetworkError(), IOCP_WSABUF_SIZE, iocpFd, isShutdown, onAlpnGet(), onPreRead(), onReadCompleted(), onWriteCompleted(), postRead(), sese::_windows::iocp::v1::NativeContext::READ, sese::_windows::iocp::v1::NativeContext::READY, releaseContext(), and sese::_windows::iocp::v1::NativeContext::WRITE.
Referenced by init().
getDeleteContextCallback()
const DeleteContextCallback & sese::_windows::iocp::v1::NativeIOCPServer::getDeleteContextCallback () const inline nodiscard
Get the current service operation context destruction callback function
Returns
Callback function
References deleteContextCallback.
getServCtx()
const security::SSLContext::Ptr & sese::_windows::iocp::v1::NativeIOCPServer::getServCtx () const inline nodiscard
Get the current server listening SSL context
Returns
SSL context
References sslCtx.
init()
bool NativeIOCPServer::init ()
Initialize and start the server
Returns
The result of initialization
References acceptThread, acceptThreadProc(), address, alpnCallbackFunction(), sese::net::Socket::bind(), bioCtrl(), bioMethod, bioRead(), bioWrite(), sese::net::Socket::close(), eventThreadGroup, eventThreadProc(), sese::net::IPAddress::getFamily(), sese::net::Address::getRawAddress(), sese::net::Address::getRawAddressLength(), initConnectEx(), iocpFd, sese::net::Socket::listen(), listenFd, sese::net::Socket::setNonblocking(), sslCtx, and threads.
initConnectEx()
bool NativeIOCPServer::initConnectEx () protected
References sese::net::Socket::close(), and connectEx.
Referenced by init().
isActiveReleaseMode()
bool sese::_windows::iocp::v1::NativeIOCPServer::isActiveReleaseMode () const inline
Get the active release mode status
Returns
Active release mode status
References activeReleaseMode.
onAcceptCompleted()
virtual void sese::_windows::iocp::v1::NativeIOCPServer::onAcceptCompleted (Context * ctx) inline virtual
Connection handshake completion callback function
Parameters
ctx The operation context
Referenced by acceptThreadProc().
onAlpnGet()
virtual void sese::_windows::iocp::v1::NativeIOCPServer::onAlpnGet (Context * ctx, const uint8_t * in, uint32_t in_length) inline virtual
ALPN protocol negotiation completion callback function
Parameters
ctx The context
in The negotiation content
in_length The length of the negotiation content
Referenced by acceptThreadProc(), and eventThreadProc().
onAlpnSelect()
int NativeIOCPServer::onAlpnSelect (const uint8_t ** out, uint8_t * out_length, const uint8_t * in, uint32_t in_length)
ALPN negotiation callback function
Parameters
out The expected content from the peer
out_length The length of the expected content from the peer
in The response content
in_length The length of the response content
Returns
The ALPN status code
References in(), and servProtos.
Referenced by alpnCallbackFunction().
onConnected()
virtual void sese::_windows::iocp::v1::NativeIOCPServer::onConnected (Context * ctx) inline virtual
Connection event callback function
Parameters
ctx The operation context
onDeleteContext()
static void sese::_windows::iocp::v1::NativeIOCPServer::onDeleteContext (Context *) inline static
Default context release callback function
onPreConnect()
virtual void sese::_windows::iocp::v1::NativeIOCPServer::onPreConnect (Context * ctx) inline virtual
Pre-connection event callback function
Parameters
ctx The operation context
Referenced by postConnect().
onPreRead()
virtual void sese::_windows::iocp::v1::NativeIOCPServer::onPreRead (Context * ctx) inline virtual
Read event trigger callback function
Parameters
ctx The operation context
Referenced by eventThreadProc().
onReadCompleted()
virtual void sese::_windows::iocp::v1::NativeIOCPServer::onReadCompleted (Context * ctx) inline virtual
Read event completion callback function
Parameters
ctx The operation context
Referenced by eventThreadProc().
onTimeout()
virtual void sese::_windows::iocp::v1::NativeIOCPServer::onTimeout (Context * ctx) inline virtual
Timeout event callback function
Parameters
ctx Operation context
Referenced by setTimeout().
onWriteCompleted()
virtual void sese::_windows::iocp::v1::NativeIOCPServer::onWriteCompleted (Context * ctx) inline virtual
Write event completion callback function
Parameters
ctx The operation context
Referenced by eventThreadProc().
postClose()
void NativeIOCPServer::postClose (NativeIOCPServer::Context * ctx)
Post a close event
Parameters
ctx The operation context
References activeReleaseMode, sese::_windows::iocp::v1::NativeContext::CLOSE, iocpFd, sese::_windows::iocp::v1::NativeContext::pWrapper, releaseContext(), and sese::_windows::iocp::v1::NativeContext::type.
postConnect()
void NativeIOCPServer::postConnect (const net::IPAddress::Ptr & to, const security::SSLContext::Ptr & cli_ctx, void * data = nullptr)
Post a connection event
Parameters
to The connection address
cli_ctx The SSL client context
data The additional data
References sese::net::IPv4Address::any(), sese::net::IPv6Address::any(), sese::net::Socket::bind(), clientProtos, sese::_windows::iocp::v1::NativeContext::CONNECT, ConnectEx, e, sese::net::IPAddress::getFamily(), sese::net::getNetworkError(), sese::net::Address::getRawAddress(), sese::net::Address::getRawAddressLength(), iocpFd, onPreConnect(), releaseContext(), sese::net::Socket::setNonblocking(), sese::net::Socket::socket(), wrapperSet, and wrapperSetMutex.
postRead()
void NativeIOCPServer::postRead (NativeIOCPServer::Context * ctx)
Post a read event
Parameters
ctx The operation context
References sese::iocp::IOBufNode::buffer, sese::iocp::IOBufNode::CAPACITY, e, sese::_windows::iocp::v1::NativeContext::fd, sese::net::getNetworkError(), IOCP_WSABUF_SIZE, sese::_windows::iocp::v1::OverlappedWrapper::overlapped, sese::_windows::iocp::v1::NativeContext::pWrapper, sese::_windows::iocp::v1::NativeContext::READ, sese::_windows::iocp::v1::NativeContext::readNode, releaseContext(), sese::_windows::iocp::v1::NativeContext::type, and sese::_windows::iocp::v1::NativeContext::wsabufRead.
Referenced by eventThreadProc().
postWrite()
void NativeIOCPServer::postWrite (NativeIOCPServer::Context * ctx)
Post a write event
Parameters
ctx The operation context
References e, sese::_windows::iocp::v1::NativeContext::fd, sese::net::getNetworkError(), IOCP_WSABUF_SIZE, sese::_windows::iocp::v1::OverlappedWrapper::overlapped, sese::io::AbstractByteBuffer::peek(), sese::_windows::iocp::v1::NativeContext::pWrapper, releaseContext(), sese::_windows::iocp::v1::NativeContext::send, sese::_windows::iocp::v1::NativeContext::type, sese::_windows::iocp::v1::NativeContext::WRITE, and sese::_windows::iocp::v1::NativeContext::wsabufWrite.
releaseContext()
void NativeIOCPServer::releaseContext (Context * ctx) protected
Release the operation context
Parameters
ctx The operation context to be released
References sese::TimeWheel::cancel(), sese::net::Socket::close(), sese::_windows::iocp::v1::NativeContext::pWrapper, wheel, wrapperSet, and wrapperSetMutex.
Referenced by eventThreadProc(), postClose(), postConnect(), postRead(), and postWrite().
setActiveReleaseMode()
void sese::_windows::iocp::v1::NativeIOCPServer::setActiveReleaseMode (bool enable) inline protected
Set the active release mode
Parameters
enable Whether to enable
References activeReleaseMode.
setAddress()
void sese::_windows::iocp::v1::NativeIOCPServer::setAddress (const net::IPAddress::Ptr & addr) inline
Set the IP address bound to the current service. By setting this option, the server will automatically listen on the corresponding address's port.
Parameters
addr Target IP
References address.
setClientProtos()
void sese::_windows::iocp::v1::NativeIOCPServer::setClientProtos (const std::string & protos) inline
Set the ALPN protocol negotiation content for the client
Parameters
protos Protocol negotiation content
References clientProtos.
setDeleteContextCallback()
void sese::_windows::iocp::v1::NativeIOCPServer::setDeleteContextCallback (const DeleteContextCallback & callback) inline
Set the server operation context destruction callback function
Parameters
callback Callback function
References callback(), and deleteContextCallback.
setServCtx()
void sese::_windows::iocp::v1::NativeIOCPServer::setServCtx (const security::SSLContext::Ptr & ctx) inline
Set the SSL context used for server listening
Parameters
ctx SSL context
References sslCtx.
setServProtos()
void sese::_windows::iocp::v1::NativeIOCPServer::setServProtos (const std::string & protos) inline
Set the ALPN protocol negotiation content for the server
Parameters
protos Protocol negotiation content
References servProtos.
setThreads()
void sese::_windows::iocp::v1::NativeIOCPServer::setThreads (size_t number_of_threads) inline
Set the expected number of threads for the service
Parameters
number_of_threads Number of threads
References threads.
setTimeout()
void NativeIOCPServer::setTimeout (NativeIOCPServer::Context * ctx, int64_t seconds)
Set a timeout event
Parameters
ctx The operation context
seconds The timeout duration
References sese::TimeWheel::delay(), onTimeout(), sese::_windows::iocp::v1::NativeContext::timeoutEvent, wheel, and wrapperSetMutex.
shutdown()
void NativeIOCPServer::shutdown ()
Terminate worker threads, release system resources, and shut down the server
References acceptThread, bioMethod, sese::net::Socket::close(), deleteContextCallback, eventThreadGroup, iocpFd, isShutdown, threads, and wrapperSet.
Member Data Documentation
acceptThread
Thread::Ptr sese::_windows::iocp::v1::NativeIOCPServer::acceptThread {} protected
Referenced by init(), and shutdown().
activeReleaseMode
bool sese::_windows::iocp::v1::NativeIOCPServer::activeReleaseMode = true private
Referenced by eventThreadProc(), isActiveReleaseMode(), postClose(), and setActiveReleaseMode().
address
net::IPAddress::Ptr sese::_windows::iocp::v1::NativeIOCPServer::address {} protected
Referenced by init(), and setAddress().
bioMethod
void* sese::_windows::iocp::v1::NativeIOCPServer::bioMethod {} protected
Referenced by acceptThreadProc(), eventThreadProc(), init(), and shutdown().
clientProtos
std::string sese::_windows::iocp::v1::NativeIOCPServer::clientProtos {} protected
Referenced by postConnect(), and setClientProtos().
connectEx
void* sese::_windows::iocp::v1::NativeIOCPServer::connectEx {} protected
Referenced by initConnectEx().
deleteContextCallback
DeleteContextCallback sese::_windows::iocp::v1::NativeIOCPServer::deleteContextCallback = onDeleteContext protected
Referenced by getDeleteContextCallback(), setDeleteContextCallback(), and shutdown().
eventThreadGroup
std::vector<Thread::Ptr> sese::_windows::iocp::v1::NativeIOCPServer::eventThreadGroup {} protected
Referenced by init(), and shutdown().
iocpFd
HANDLE sese::_windows::iocp::v1::NativeIOCPServer::iocpFd {INVALID_HANDLE_VALUE} protected
Referenced by acceptThreadProc(), eventThreadProc(), init(), postClose(), postConnect(), and shutdown().
isShutdown
std::atomic_bool sese::_windows::iocp::v1::NativeIOCPServer::isShutdown {false} protected
Referenced by acceptThreadProc(), eventThreadProc(), and shutdown().
listenFd
SOCKET sese::_windows::iocp::v1::NativeIOCPServer::listenFd {INVALID_SOCKET} protected
Referenced by acceptThreadProc(), and init().
servProtos
std::string sese::_windows::iocp::v1::NativeIOCPServer::servProtos {} protected
Referenced by onAlpnSelect(), and setServProtos().
sslCtx
security::SSLContext::Ptr sese::_windows::iocp::v1::NativeIOCPServer::sslCtx {} protected
Referenced by acceptThreadProc(), getServCtx(), init(), and setServCtx().
threads
size_t sese::_windows::iocp::v1::NativeIOCPServer::threads {2} protected
Referenced by init(), setThreads(), and shutdown().
wheel
TimeWheel sese::_windows::iocp::v1::NativeIOCPServer::wheel {} protected
Referenced by acceptThreadProc(), cancelTimeout(), releaseContext(), and setTimeout().
wrapperSet
std::set<OverlappedWrapper *> sese::_windows::iocp::v1::NativeIOCPServer::wrapperSet {} protected
Referenced by acceptThreadProc(), postConnect(), releaseContext(), and shutdown().
wrapperSetMutex
std::mutex sese::_windows::iocp::v1::NativeIOCPServer::wrapperSetMutex {} protected
Referenced by acceptThreadProc(), cancelTimeout(), postConnect(), releaseContext(), and setTimeout().
The documentation for this class was generated from the following files:
sese/native/win/service/iocp/NativeIOCPServer_V1.h
sese/native/win/service/iocp/NativeIOCPServer_V1.cpp