Sese Framework: sese::internal::net::http::HttpSSLClientImpl Class Reference
sese::internal::net::http::HttpSSLClientImpl Class Reference final
HTTP/1.1 client based on ASIO.
#include <HttpSSLClientImpl.h>
Public Member Functions
HttpSSLClientImpl (const sese::net::IPAddress::Ptr &addr, sese::net::http::Request::Ptr req)
Public Member Functions inherited from sese::internal::net::http::HttpClientImpl
HttpClientImpl (const sese::net::IPAddress::Ptr &addr, sese::net::http::Request::Ptr req)
~HttpClientImpl () override
bool request () override
int getLastError () override
std::string getLastErrorString () override
Public Member Functions inherited from sese::net::http::Requestable
~Requestable () override=default
Request::Ptr & getRequest ()
Response::Ptr & getResponse ()
void setReadData (io::PeekableStream *read_data, size_t expect_total)
void setWriteData (io::OutputStream *write_data)
void setReadCallback (const ReadCallback &read_callback, size_t expect_total)
void setWriteCallback (const WriteCallback &write_callback)
void reset ()
Reset body-related settings.
Public Member Functions inherited from sese::io::InputStream
virtual ~InputStream () noexcept=default
Public Member Functions inherited from sese::io::OutputStream
virtual ~OutputStream () noexcept=default
int64_t write (const std::string_view &buffer)
int64_t write (const text::StringView &buffer)
template<typename T >
int64_t write (std::vector< T > &buffer)
template<typename T , size_t N>
int64_t write (std::array< T, N > &buffer)
Protected Member Functions
bool handshake () override
bool shutdown () override
int64_t read (void *buffer, size_t length) override
int64_t write (const void *buffer, size_t length) override
Protected Member Functions inherited from sese::internal::net::http::HttpClientImpl
bool writeHeader (io::ByteBuilder &builder)
bool writeBodyByCallback ()
bool writeBodyByData ()
bool writeBodyByAuto ()
bool readBodyByCallback (size_t expect)
bool readBodyByData (size_t expect)
Private Attributes
asio::ssl::context sslContext
asio::ssl::stream< asio::ip::tcp::socket & > sslSocket
Additional Inherited Members
Public Types inherited from sese::net::http::Requestable
using WriteCallback = std::function<int64_t(const void *, size_t)>
using ReadCallback = std::function<int64_t(void *, size_t)>
Public Types inherited from sese::io::InputStream
typedef std::shared_ptr< InputStream > Ptr
Public Types inherited from sese::io::OutputStream
typedef std::shared_ptr< OutputStream > Ptr
Protected Attributes inherited from sese::internal::net::http::HttpClientImpl
sese::net::IPAddress::Ptr address
sese::net::http::CookieMap::Ptr cookies
asio::error_code code {}
asio::io_context ioContext
asio::ip::tcp::socket socket
bool first = true
Protected Attributes inherited from sese::net::http::Requestable
Request::Ptr req = nullptr
Response::Ptr resp = nullptr
size_t expect_total = 0
io::PeekableStream * read_data = nullptr
io::OutputStream * write_data = nullptr
WriteCallback write_callback
ReadCallback read_callback
Detailed Description
HTTP/1.1 client based on ASIO.
Constructor & Destructor Documentation
HttpSSLClientImpl()
HttpSSLClientImpl::HttpSSLClientImpl (const sese::net::IPAddress::Ptr & addr, sese::net::http::Request::Ptr req)
Member Function Documentation
handshake()
bool HttpSSLClientImpl::handshake () override protected virtual
Reimplemented from sese::internal::net::http::HttpClientImpl.
References sese::internal::net::http::HttpClientImpl::code, sese::internal::net::http::HttpClientImpl::handshake(), and sslSocket.
read()
int64_t HttpSSLClientImpl::read (void * buffer, size_t length) override protected virtual
Reimplemented from sese::internal::net::http::HttpClientImpl.
References sese::internal::net::http::HttpClientImpl::code, read(), and sslSocket.
Referenced by read().
shutdown()
bool HttpSSLClientImpl::shutdown () override protected virtual
Reimplemented from sese::internal::net::http::HttpClientImpl.
References sese::internal::net::http::HttpClientImpl::code, and sslSocket.
write()
int64_t HttpSSLClientImpl::write (const void * buffer, size_t length) override protected virtual
Reimplemented from sese::internal::net::http::HttpClientImpl.
References sese::internal::net::http::HttpClientImpl::code, and sslSocket.
Member Data Documentation
sslContext
asio::ssl::context sese::internal::net::http::HttpSSLClientImpl::sslContext private
sslSocket
asio::ssl::stream<asio::ip::tcp::socket &> sese::internal::net::http::HttpSSLClientImpl::sslSocket private
Referenced by handshake(), read(), shutdown(), and write().
The documentation for this class was generated from the following files:
sese/internal/net/http/HttpSSLClientImpl.h
sese/internal/net/http/HttpSSLClientImpl.cpp