Sese Framework: sese::db::impl::PostgresDriverInstanceImpl Class Reference
sese::db::impl::PostgresDriverInstanceImpl Class Reference
PSQL driver implementation.
#include <PostgresDriverInstanceImpl.h>
Public Member Functions
PostgresDriverInstanceImpl (PGconn *conn) noexcept
~PostgresDriverInstanceImpl () noexcept override
ResultSet::Ptr executeQuery (const char *sql) noexcept override
int64_t executeUpdate (const char *sql) noexcept override
PreparedStatement::Ptr createStatement (const char *sql) noexcept override
int getLastError () const noexcept override
const char * getLastErrorMessage () const noexcept override
bool setAutoCommit (bool enable) noexcept override
bool getAutoCommit (bool &status) noexcept override
bool begin () noexcept override
bool commit () noexcept override
bool rollback () noexcept override
bool getInsertId (int64_t &id) const noexcept override
Public Member Functions inherited from sese::db::DriverInstance
virtual ~DriverInstance () noexcept=default
Destructors.
ErrorCode getErrorCode () const
Protected Attributes
PGconn * conn
PGresult * result
int error = 0
std::random_device rd {}
Additional Inherited Members
Public Types inherited from sese::db::DriverInstance
using Ptr = std::unique_ptr<DriverInstance>
Detailed Description
PSQL driver implementation.
Constructor & Destructor Documentation
PostgresDriverInstanceImpl()
impl::PostgresDriverInstanceImpl::PostgresDriverInstanceImpl (PGconn * conn) explicit noexcept
~PostgresDriverInstanceImpl()
impl::PostgresDriverInstanceImpl::~PostgresDriverInstanceImpl () override noexcept
References conn, and result.
Member Function Documentation
begin()
bool impl::PostgresDriverInstanceImpl::begin () nodiscard override virtual noexcept
Starts the transaction
Return values
false If the transaction start fails
Implements sese::db::DriverInstance.
commit()
bool impl::PostgresDriverInstanceImpl::commit () nodiscard override virtual noexcept
Commits the transaction
Return values
false If the commit fails
Implements sese::db::DriverInstance.
createStatement()
PreparedStatement::Ptr impl::PostgresDriverInstanceImpl::createStatement (const char * sql) override virtual noexcept
Creates a prepared statement object
Parameters
sql The SQL query string
Returns
The prepared statement object
Return values
nullptr If creation fails
Implements sese::db::DriverInstance.
References sese::text::AbstractStringBuffer::append(), count(), and sese::text::AbstractStringBuffer::toString().
executeQuery()
ResultSet::Ptr impl::PostgresDriverInstanceImpl::executeQuery (const char * sql) override virtual noexcept
Execute the query
Parameters
sql Query statements
Returns
The result set that was queried
Return values
nullptr Query failed
Implements sese::db::DriverInstance.
executeUpdate()
int64_t impl::PostgresDriverInstanceImpl::executeUpdate (const char * sql) override virtual noexcept
Execute the update
Parameters
sql Update statements
Returns
Count the number of rows updated
Return values
-1 Execution failed
Implements sese::db::DriverInstance.
getAutoCommit()
bool impl::PostgresDriverInstanceImpl::getAutoCommit (bool & status) nodiscard override virtual noexcept
Checks whether auto-commit is enabled
Warning
Since libpq does not support retrieving the autoCommit status, it is recommended to use the command line to obtain this value when using PostgreSQL.
Return values
false If the operation fails
Implements sese::db::DriverInstance.
getInsertId()
bool impl::PostgresDriverInstanceImpl::getInsertId (int64_t & id) const nodiscard override virtual noexcept
Retrieves the auto-incremented ID
Warning
Since libpq does not support retrieving the auto-incremented ID, it is recommended to use the command line with the query ‘SELECT currval(pg_get_serial_sequence('tabName’, 'colName'))` to get the auto-incremented ID when using PostgreSQL.
Return values
false If the retrieval fails
Implements sese::db::DriverInstance.
getLastError()
int impl::PostgresDriverInstanceImpl::getLastError () const nodiscard override virtual noexcept
Retrieves the error code corresponding to the instance's driver
Returns
The error code
Implements sese::db::DriverInstance.
getLastErrorMessage()
const char * impl::PostgresDriverInstanceImpl::getLastErrorMessage () const nodiscard override virtual noexcept
Retrieves the error message corresponding to the instance's driver (null check required)
Returns
The error message
Implements sese::db::DriverInstance.
rollback()
bool impl::PostgresDriverInstanceImpl::rollback () nodiscard override virtual noexcept
Rolls back the transaction
Return values
false If the rollback fails
Implements sese::db::DriverInstance.
setAutoCommit()
bool impl::PostgresDriverInstanceImpl::setAutoCommit (bool enable) nodiscard override virtual noexcept
Sets the transaction auto-commit mode
Warning
Since libpq does not support setting autocommit, and the autoCommit property is global, it is recommended to use begin() to start a transaction when using PostgreSQL.
Since sqlite3 does not support setting autocommit, it is recommended to use begin() to start a transaction when using SQLite.
Parameters
enable Enable or disable auto-commit mode
Return values
false If the operation fails
Implements sese::db::DriverInstance.
Member Data Documentation
conn
PGconn* sese::db::impl::PostgresDriverInstanceImpl::conn protected
Referenced by ~PostgresDriverInstanceImpl().
error
int sese::db::impl::PostgresDriverInstanceImpl::error = 0 protected
rd
std::random_device sese::db::impl::PostgresDriverInstanceImpl::rd {} protected
result
PGresult* sese::db::impl::PostgresDriverInstanceImpl::result protected
Referenced by ~PostgresDriverInstanceImpl().
The documentation for this class was generated from the following files:
sese/internal/db/pgsql/PostgresDriverInstanceImpl.h
sese/internal/db/pgsql/PostgresDriverInstanceImpl.cpp