Sese Framework: sese::log::Logger Class Reference
sese::log::Logger Class Reference
Logger class.
#include <Logger.h>
Classes
struct PatternAndLocation
Public Types
typedef std::shared_ptr< Logger > Ptr
Public Member Functions
Logger () noexcept
virtual ~Logger () noexcept=default
void addAppender (const AbstractAppender::Ptr &appender) noexcept
void removeAppender (const AbstractAppender::Ptr &appender) noexcept
virtual void log (const Event::Ptr &event) noexcept
virtual void dump (const void *buffer, size_t length) noexcept
Static Public Member Functions
template<typename... ARGS>
static void debug (PatternAndLocation pattern_and_location, ARGS &&...args)
static void debug (PatternAndLocation pattern_and_location)
template<typename... ARGS>
static void info (PatternAndLocation pattern_and_location, ARGS &&...args)
static void info (PatternAndLocation pattern_and_location)
template<typename... ARGS>
static void warn (PatternAndLocation pattern_and_location, ARGS &&...args)
static void warn (PatternAndLocation pattern_and_location)
template<typename... ARGS>
static void error (PatternAndLocation pattern_and_location, ARGS &&...args)
static void error (PatternAndLocation pattern_and_location)
static void addGlobalLoggerAppender (const AbstractAppender::Ptr &appender) noexcept
static void removeGlobalLoggerAppender (const AbstractAppender::Ptr &appender) noexcept
Protected Attributes
std::shared_ptr< AbstractFormatter > formatter
std::shared_ptr< ConsoleAppender > builtInAppender
std::vector< AbstractAppender::Ptr > appenderVector
Static Private Member Functions
static void prelog (PatternAndLocation &pattern_and_location, Level level, const std::string &string) noexcept
Detailed Description
Logger class.
Member Typedef Documentation
Ptr
typedef std::shared_ptr<Logger> sese::log::Logger::Ptr
Constructor & Destructor Documentation
Logger()
sese::log::Logger::Logger () noexcept
References builtInAppender, sese::log::DEBUG, formatter, and sese::log::INFO.
~Logger()
virtual sese::log::Logger::~Logger () virtual default noexcept
Member Function Documentation
addAppender()
void sese::log::Logger::addAppender (const AbstractAppender::Ptr & appender) noexcept
Add log appender
Parameters
appender Log appender
Referenced by addGlobalLoggerAppender().
addGlobalLoggerAppender()
void sese::log::Logger::addGlobalLoggerAppender (const AbstractAppender::Ptr & appender) static noexcept
Add log appender to global logger
Parameters
appender Log appender
References addAppender(), and sese::log::logger.
debug() [1/2]
void sese::log::Logger::debug (PatternAndLocation pattern_and_location) static
References sese::log::DEBUG, sese::log::Logger::PatternAndLocation::pattern, and prelog().
debug() [2/2]
template<typename... ARGS> void sese::log::Logger::debug (PatternAndLocation pattern_and_location, ARGS &&... args) static
References sese::log::DEBUG, and sese::text::fmt().
dump()
void sese::log::Logger::dump (const void * buffer, size_t length) virtual noexcept
Output raw content
Parameters
buffer Buffer
length Length of buffer
Reimplemented in sese::log::AsyncLogger.
Referenced by sese::Exception::printStacktrace().
error() [1/2]
void sese::log::Logger::error (PatternAndLocation pattern_and_location) static
References sese::log::ERR, sese::log::Logger::PatternAndLocation::pattern, and prelog().
error() [2/2]
template<typename... ARGS> void sese::log::Logger::error (PatternAndLocation pattern_and_location, ARGS &&... args) static
References sese::log::ERR, sese::text::fmt(), and sese::log::Logger::PatternAndLocation::pattern.
info() [1/2]
void sese::log::Logger::info (PatternAndLocation pattern_and_location) static
References sese::log::INFO, sese::log::Logger::PatternAndLocation::pattern, and prelog().
info() [2/2]
template<typename... ARGS> void sese::log::Logger::info (PatternAndLocation pattern_and_location, ARGS &&... args) static
References sese::text::fmt(), sese::log::INFO, and sese::log::Logger::PatternAndLocation::pattern.
log()
void sese::log::Logger::log (const Event::Ptr & event) virtual noexcept
Output log
Parameters
event Log event
Reimplemented in sese::log::AsyncLogger.
References sese::log::DEBUG, sese::log::ERR, sese::log::INFO, sese::log::ConsoleAppender::setCleanColor(), sese::log::ConsoleAppender::setDebugColor(), sese::log::ConsoleAppender::setErrorColor(), sese::log::ConsoleAppender::setInfoColor(), sese::log::ConsoleAppender::setWarnColor(), and sese::log::WARN.
Referenced by prelog().
prelog()
void sese::log::Logger::prelog (PatternAndLocation & pattern_and_location, Level level, const std::string & string) static private noexcept
References sese::Thread::getCurrentThreadId(), sese::Thread::getCurrentThreadName(), log(), sese::log::logger, and sese::DateTime::now().
Referenced by debug(), error(), info(), and warn().
removeAppender()
void sese::log::Logger::removeAppender (const AbstractAppender::Ptr & appender) noexcept
Remove log appender
Parameters
appender Log appender
Referenced by removeGlobalLoggerAppender().
removeGlobalLoggerAppender()
void sese::log::Logger::removeGlobalLoggerAppender (const AbstractAppender::Ptr & appender) static noexcept
Remove log appender from global logger
Parameters
appender Log appender
References sese::log::logger, and removeAppender().
warn() [1/2]
void sese::log::Logger::warn (PatternAndLocation pattern_and_location) static
References sese::log::Logger::PatternAndLocation::pattern, prelog(), and sese::log::WARN.
warn() [2/2]
template<typename... ARGS> void sese::log::Logger::warn (PatternAndLocation pattern_and_location, ARGS &&... args) static
References sese::text::fmt(), sese::log::Logger::PatternAndLocation::pattern, and sese::log::WARN.
Member Data Documentation
appenderVector
std::vector<AbstractAppender::Ptr> sese::log::Logger::appenderVector protected
Referenced by sese::log::AsyncLogger::loop().
builtInAppender
std::shared_ptr<ConsoleAppender> sese::log::Logger::builtInAppender protected
Referenced by Logger(), and sese::log::AsyncLogger::loop().
formatter
std::shared_ptr<AbstractFormatter> sese::log::Logger::formatter protected
Referenced by Logger().
The documentation for this class was generated from the following files:
sese/log/Logger.h
sese/log/Logger.cpp