Sese Framework: sese::record::BlockAppender Class Reference
sese::record::BlockAppender Class Reference final
Block file log appender class.
#include <BlockAppender.h>
Public Member Functions
BlockAppender (size_t block_max_size, Level level=Level::DEBUG)
~BlockAppender () noexcept override
void dump (const char *buffer, size_t size) noexcept override
Public Member Functions inherited from sese::record::AbstractAppender
AbstractAppender () noexcept=default
virtual ~AbstractAppender () noexcept=default
AbstractAppender (Level level) noexcept
Level getLevel () const noexcept
void setLevel (Level lv) noexcept
Private Attributes
size_t size = 0
std::mutex mutex
size_t maxSize = 0
io::BufferedStream::Ptr bufferedStream
io::FileStream::Ptr fileStream
Additional Inherited Members
Public Types inherited from sese::record::AbstractAppender
typedef std::shared_ptr< AbstractAppender > Ptr
Protected Attributes inherited from sese::record::AbstractAppender
Level level = Level::DEBUG
Output threshold.
Detailed Description
Block file log appender class.
Constructor & Destructor Documentation
BlockAppender()
BlockAppender::BlockAppender (size_t block_max_size, Level level = Level::DEBUG) explicit
Initialize block parameters
Parameters
block_max_size Preset size of the block. This parameter has a minimum value limit in non-DEBUG mode, at least 1000 * 1024, which is 1MB
level Threshold level
References bufferedStream, sese::io::FileStream::create(), fileStream, getDateTimeString(), maxSize, and sese::io::FileStream::T_WRITE_TRUNC.
~BlockAppender()
BlockAppender::~BlockAppender () override noexcept
References bufferedStream, and fileStream.
Member Function Documentation
dump()
void BlockAppender::dump (const char * buffer, size_t size) override virtual noexcept
Implements sese::record::AbstractAppender.
References sese::io::FileStream::create(), getDateTimeString(), and sese::io::FileStream::T_WRITE_TRUNC.
Member Data Documentation
bufferedStream
io::BufferedStream::Ptr sese::record::BlockAppender::bufferedStream private
Referenced by BlockAppender(), and ~BlockAppender().
fileStream
io::FileStream::Ptr sese::record::BlockAppender::fileStream private
Referenced by BlockAppender(), and ~BlockAppender().
maxSize
size_t sese::record::BlockAppender::maxSize = 0 private
Referenced by BlockAppender().
mutex
std::mutex sese::record::BlockAppender::mutex private
size
size_t sese::record::BlockAppender::size = 0 private
The documentation for this class was generated from the following files:
sese/record/BlockAppender.h
sese/record/BlockAppender.cpp