Sese Framework: sese::xml::XmlUtil Class Reference
sese::xml::XmlUtil Class Reference final
XML Serialization Utility Class.
#include <XmlUtil.h>
Public Types
using InputStream = io::InputStream
using OutputStream = io::OutputStream
using Tokens = std::queue<std::string>
Public Member Functions
XmlUtil ()=delete
Public Member Functions inherited from sese::NotInstantiable
NotInstantiable ()=delete
virtual ~NotInstantiable ()=default
NotInstantiable (const NotInstantiable &)=delete
NotInstantiable & operator= (const NotInstantiable &)=delete
Static Public Member Functions
static Element::Ptr deserialize (const InputStream::Ptr &input_stream, size_t level) noexcept
static Element::Ptr deserialize (InputStream *input_stream, size_t level) noexcept
static void serialize (const Element::Ptr &object, const OutputStream::Ptr &output_stream) noexcept
static void serialize (const Element::Ptr &object, OutputStream *output_stream) noexcept
Static Private Member Functions
static void tokenizer (InputStream *input_stream, Tokens &tokens) noexcept
static bool removeComment (Tokens &tokens) noexcept
static Element::Ptr createElement (Tokens &tokens, size_t level, bool is_sub_element) noexcept
Detailed Description
XML Serialization Utility Class.
Member Typedef Documentation
InputStream
using sese::xml::XmlUtil::InputStream = io::InputStream
OutputStream
using sese::xml::XmlUtil::OutputStream = io::OutputStream
Tokens
using sese::xml::XmlUtil::Tokens = std::queue<std::string>
Constructor & Destructor Documentation
XmlUtil()
sese::xml::XmlUtil::XmlUtil () delete
Member Function Documentation
createElement()
Element::Ptr sese::xml::XmlUtil::createElement (Tokens & tokens, size_t level, bool is_sub_element) static private noexcept
References sese::text::AbstractStringBuffer::append(), CHECK, and sese::text::AbstractStringBuffer::toString().
deserialize() [1/2]
Element::Ptr sese::xml::XmlUtil::deserialize (const InputStream::Ptr & input_stream, size_t level) static noexcept
Deserialize an XML element object from a stream
Parameters
input_stream Input stream
level Deserialization depth
Return values
nullptr Deserialization failed, otherwise succeeded
deserialize() [2/2]
Element::Ptr sese::xml::XmlUtil::deserialize (InputStream * input_stream, size_t level) static noexcept
Deserialize an XML element object from a stream
Parameters
input_stream Input stream
level Deserialization depth
Return values
nullptr Deserialization failed, otherwise succeeded
removeComment()
bool sese::xml::XmlUtil::removeComment (Tokens & tokens) static private noexcept
serialize() [1/2]
void sese::xml::XmlUtil::serialize (const Element::Ptr & object, const OutputStream::Ptr & output_stream) static noexcept
Serialize an XML element object to a stream
Parameters
object Object to be serialized
output_stream Output stream
serialize() [2/2]
void sese::xml::XmlUtil::serialize (const Element::Ptr & object, OutputStream * output_stream) static noexcept
Serialize an XML element object to a stream
Parameters
object Object to be serialized
output_stream Output stream
tokenizer()
void sese::xml::XmlUtil::tokenizer (InputStream * input_stream, Tokens & tokens) static private noexcept
References sese::text::AbstractStringBuffer::append(), sese::text::AbstractStringBuffer::clear(), sese::text::AbstractStringBuffer::empty(), sese::isSpace(), and sese::text::AbstractStringBuffer::toString().
The documentation for this class was generated from the following files:
sese/config/xml/XmlUtil.h
sese/config/xml/XmlUtil.cpp