Sese Framework: sese::log::SimpleFormatter Class Reference
sese::log::SimpleFormatter Class Reference final
Simple formatter class.
#include <SimpleFormatter.h>
Public Member Functions
SimpleFormatter (const std::string &text_pattern=RECORD_DEFAULT_TEXT_PATTERN, const std::string &time_pattern=RECORD_DEFAULT_TIME_PATTERN) noexcept
std::string dump (const Event::Ptr &event) noexcept override
const char * getTextPattern () const noexcept
const char * getTimePattern () const noexcept
Public Member Functions inherited from sese::log::AbstractFormatter
virtual ~AbstractFormatter () noexcept=default
Private Attributes
std::string textPattern
std::string timePattern
Additional Inherited Members
Public Types inherited from sese::log::AbstractFormatter
typedef std::shared_ptr< AbstractFormatter > Ptr
Detailed Description
Simple formatter class.
Constructor & Destructor Documentation
SimpleFormatter()
sese::log::SimpleFormatter::SimpleFormatter (const std::string & text_pattern = RECORD_DEFAULT_TEXT_PATTERN, const std::string & time_pattern = RECORD_DEFAULT_TIME_PATTERN) explicit noexcept
Default constructor
Parameters
text_pattern Format string, default is RECORD_DEFAULT_TEXT_PATTERN
See also
RECORD_DEFAULT_TEXT_PATTERN
* %    Escape symbol
* li   Line number
* lv   Log level
* fn   File name
* th   Thread ID
* tn   Thread name
* c    Complete time
* m    Content
*
Parameters
time_pattern Time format string
Member Function Documentation
dump()
std::string sese::log::SimpleFormatter::dump (const Event::Ptr & event) override virtual noexcept
Implements sese::log::AbstractFormatter.
References sese::text::AbstractStringBuffer::append(), sese::text::DateTimeFormatter::format(), sese::getLevelString(), and sese::text::AbstractStringBuffer::toString().
getTextPattern()
const char * sese::log::SimpleFormatter::getTextPattern () const inline nodiscard noexcept
References textPattern.
getTimePattern()
const char * sese::log::SimpleFormatter::getTimePattern () const inline nodiscard noexcept
References timePattern.
Member Data Documentation
textPattern
std::string sese::log::SimpleFormatter::textPattern private
Referenced by getTextPattern().
timePattern
std::string sese::log::SimpleFormatter::timePattern private
Referenced by getTimePattern().
The documentation for this class was generated from the following files:
sese/log/SimpleFormatter.h
sese/log/SimpleFormatter.cpp