Sese Framework: sese::text::AbstractStringBuffer Class Reference
sese::text::AbstractStringBuffer Class Reference
String buffer class.
#include <AbstractStringBuffer.h>
Public Member Functions
AbstractStringBuffer (size_t cap=STRING_BUFFER_SIZE_FACTOR) noexcept
AbstractStringBuffer (const char *str) noexcept
Initialize with a string.
virtual ~AbstractStringBuffer () noexcept
AbstractStringBuffer (const AbstractStringBuffer &abstract_string_buffer) noexcept
AbstractStringBuffer (AbstractStringBuffer &&abstract_string_buffer) noexcept
virtual void append (char ch) noexcept
virtual void append (const char *str) noexcept
virtual void append (const std::string &str) noexcept
virtual void append (const std::string_view &str) noexcept
virtual void append (const String &str) noexcept
virtual void append (const StringView &view) noexcept
virtual void append (const char *data, size_t len) noexcept
virtual size_t length () const noexcept
virtual size_t size () const noexcept
virtual bool empty () const noexcept
virtual void clear () noexcept
virtual void reverse () noexcept
virtual char getCharAt (int index) const
virtual bool setChatAt (int index, char ch)
virtual bool delCharAt (int index)
virtual bool del (int start, int l)
virtual bool insertAt (int index, const char *str)
virtual bool insertAt (int index, const std::string &str)
virtual bool insertAt (int index, const std::string_view &str)
virtual bool insertAt (int index, const String &str)
virtual bool insertAt (int index, const StringView &view)
virtual void trim () noexcept
Remove whitespace at both ends.
virtual std::vector< std::string > split (const std::string_view &str) const noexcept
virtual bool startsWith (const std::string_view &prefix) const noexcept
virtual bool endsWith (const std::string_view &suffix) const noexcept
virtual std::string toString ()
virtual String toSString ()
virtual void * buf ()
Static Public Member Functions
static std::vector< std::string > split (const std::string_view &text, const std::string_view &sub) noexcept
static bool startsWith (const std::string_view &text, const std::string_view &prefix) noexcept
static bool endsWith (const std::string_view &text, const std::string_view &suffix) noexcept
Protected Member Functions
void expansion (size_t new_size) noexcept
String caching.
bool insertAt (int index, const char *data, size_t len)
Protected Attributes
size_t cap {}
size_t len = 0
Actual capacity.
char * buffer = nullptr
String length.
Detailed Description
String buffer class.
Constructor & Destructor Documentation
AbstractStringBuffer() [1/4]
sese::text::AbstractStringBuffer::AbstractStringBuffer (size_t cap = STRING_BUFFER_SIZE_FACTOR) explicit noexcept
Parameters
cap Initial capacity
AbstractStringBuffer() [2/4]
sese::text::AbstractStringBuffer::AbstractStringBuffer (const char * str) explicit noexcept
Initialize with a string.
Parameters
str String
References STRING_BUFFER_SIZE_FACTOR.
~AbstractStringBuffer()
sese::text::AbstractStringBuffer::~AbstractStringBuffer () virtual noexcept
References buffer.
AbstractStringBuffer() [3/4]
sese::text::AbstractStringBuffer::AbstractStringBuffer (const AbstractStringBuffer & abstract_string_buffer) noexcept
AbstractStringBuffer() [4/4]
sese::text::AbstractStringBuffer::AbstractStringBuffer (AbstractStringBuffer && abstract_string_buffer) noexcept
Member Function Documentation
append() [1/7]
void sese::text::AbstractStringBuffer::append (char ch) virtual noexcept
Reimplemented in sese::text::StringBuffer.
References append().
Referenced by append(), append(), append(), append(), append(), append(), sese::Exception::buildStacktrace(), sese::xml::XmlUtil::createElement(), sese::db::impl::PostgresDriverInstanceImpl::createStatement(), sese::PercentConverter::decode(), sese::SymbolConverter::decodeUnixClassName(), sese::net::dns::DnsPackage::decodeWords(), sese::record::SimpleFormatter::dump(), sese::PercentConverter::encode(), sese::net::dns::DnsPackage::encodeWords(), sese::net::dns::DnsPackage::Index::encodeWords(), sese::text::FormatOption_FloatNumberFormat(), sese::net::http::HttpUtil::getLine(), sese::net::http::RequestHeader::getUrl(), sese::RandomUtil::nextString(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), sese::io::InputStreamReader::readLine(), sese::Json::tokenizer(), and sese::xml::XmlUtil::tokenizer().
append() [2/7]
void sese::text::AbstractStringBuffer::append (const char * data, size_t len) virtual noexcept
Reimplemented in sese::text::StringBuffer.
References STRING_BUFFER_SIZE_FACTOR.
append() [3/7]
void sese::text::AbstractStringBuffer::append (const char * str) virtual noexcept
Reimplemented in sese::text::StringBuffer.
References append().
append() [4/7]
void sese::text::AbstractStringBuffer::append (const std::string & str) virtual noexcept
Reimplemented in sese::text::StringBuffer.
References append().
append() [5/7]
void sese::text::AbstractStringBuffer::append (const std::string_view & str) virtual noexcept
Reimplemented in sese::text::StringBuffer.
References append().
append() [6/7]
void sese::text::AbstractStringBuffer::append (const String & str) virtual noexcept
Reimplemented in sese::text::StringBuffer.
References append(), and sstr::SStringView::len().
append() [7/7]
void sese::text::AbstractStringBuffer::append (const StringView & view) virtual noexcept
Reimplemented in sese::text::StringBuffer.
References append().
buf()
void * sese::text::AbstractStringBuffer::buf () virtual
References buffer.
clear()
void sese::text::AbstractStringBuffer::clear () virtual noexcept
Reimplemented in sese::text::StringBuffer.
References len.
Referenced by sese::text::StringBuffer::clear(), sese::CSVReader::read(), sese::io::InputStreamReader::readLine(), sese::net::http::HttpUtil::recvRequest(), sese::net::http::HttpUtil::recvResponse(), sese::Json::tokenizer(), sese::xml::XmlUtil::tokenizer(), and sese::Yaml::tokenizer().
del()
bool sese::text::AbstractStringBuffer::del (int start, int l) virtual
Reimplemented in sese::text::StringBuffer.
References buffer, and len.
Referenced by sese::text::StringBuffer::del().
delCharAt()
bool sese::text::AbstractStringBuffer::delCharAt (int index) virtual
Reimplemented in sese::text::StringBuffer.
References buffer, CheckRange, and len.
Referenced by sese::text::StringBuffer::delCharAt().
empty()
virtual bool sese::text::AbstractStringBuffer::empty () const inline nodiscard virtual noexcept
Reimplemented in sese::text::StringBuffer.
References len.
Referenced by sese::text::StringBuffer::empty(), sese::Yaml::getLine(), sese::CSVReader::read(), sese::io::InputStreamReader::readLine(), and sese::xml::XmlUtil::tokenizer().
endsWith() [1/2]
bool sese::text::AbstractStringBuffer::endsWith (const std::string_view & suffix) const nodiscard virtual noexcept
endsWith() [2/2]
bool sese::text::AbstractStringBuffer::endsWith (const std::string_view & text, const std::string_view & suffix) static noexcept
Referenced by sese::text::StringBuffer::endsWith().
expansion()
void sese::text::AbstractStringBuffer::expansion (size_t new_size) protected noexcept
String caching.
Expansion
Parameters
new_size Size after expansion
Referenced by insertAt().
getCharAt()
char sese::text::AbstractStringBuffer::getCharAt (int index) const nodiscard virtual
Reimplemented in sese::text::StringBuffer.
References buffer, cap, and CheckRange.
Referenced by sese::text::StringBuffer::getCharAt().
insertAt() [1/6]
bool sese::text::AbstractStringBuffer::insertAt (int index, const char * data, size_t len) protected
References buffer, cap, expansion(), len, and STRING_BUFFER_SIZE_FACTOR.
Referenced by insertAt(), insertAt(), insertAt(), insertAt(), insertAt(), sese::text::StringBuffer::insertAt(), sese::text::StringBuffer::insertAt(), sese::text::StringBuffer::insertAt(), sese::text::StringBuffer::insertAt(), and sese::text::StringBuffer::insertAt().
insertAt() [2/6]
bool sese::text::AbstractStringBuffer::insertAt (int index, const char * str) virtual
Reimplemented in sese::text::StringBuffer.
References insertAt().
insertAt() [3/6]
bool sese::text::AbstractStringBuffer::insertAt (int index, const std::string & str) virtual
Reimplemented in sese::text::StringBuffer.
References insertAt().
insertAt() [4/6]
bool sese::text::AbstractStringBuffer::insertAt (int index, const std::string_view & str) virtual
Reimplemented in sese::text::StringBuffer.
References insertAt().
insertAt() [5/6]
bool sese::text::AbstractStringBuffer::insertAt (int index, const String & str) virtual
Reimplemented in sese::text::StringBuffer.
References insertAt(), and sstr::SStringView::len().
insertAt() [6/6]
bool sese::text::AbstractStringBuffer::insertAt (int index, const StringView & view) virtual
Reimplemented in sese::text::StringBuffer.
References sstr::SStringView::data(), insertAt(), and sstr::SStringView::len().
length()
virtual size_t sese::text::AbstractStringBuffer::length () const inline nodiscard virtual noexcept
Reimplemented in sese::text::StringBuffer.
References len.
Referenced by sese::text::StringBuffer::length().
reverse()
void sese::text::AbstractStringBuffer::reverse () virtual noexcept
Reimplemented in sese::text::StringBuffer.
References buffer, and len.
Referenced by sese::text::StringBuffer::reverse().
setChatAt()
bool sese::text::AbstractStringBuffer::setChatAt (int index, char ch) virtual
Reimplemented in sese::text::StringBuffer.
References buffer, cap, and CheckRange.
Referenced by sese::text::StringBuffer::setChatAt().
size()
virtual size_t sese::text::AbstractStringBuffer::size () const inline nodiscard virtual noexcept
Reimplemented in sese::text::StringBuffer.
References cap.
Referenced by sese::text::StringBuffer::size().
split() [1/2]
std::vector< std::string > sese::text::AbstractStringBuffer::split (const std::string_view & str) const nodiscard virtual noexcept
Reimplemented in sese::text::StringBuffer.
split() [2/2]
std::vector< std::string > sese::text::AbstractStringBuffer::split (const std::string_view & text, const std::string_view & sub) static noexcept
Referenced by sese::net::dns::DnsPackage::encodeWords(), sese::net::http::RequestHeader::getUrl(), sese::net::http::Range::parse(), sese::net::http::RequestParser::parse(), sese::net::http::RequestParser::parseAddress(), sese::net::http::HttpUtil::parseFromCookie(), sese::text::DateTimeFormatter::parseFromISO8601(), sese::net::http::HttpUtil::parseFromSetCookie(), sese::net::http::HttpUtil::recvRequest(), sese::net::http::HttpUtil::recvResponse(), sese::net::http::RequestHeader::setUrl(), sese::text::StringBuffer::split(), and sese::db::tokenize().
startsWith() [1/2]
bool sese::text::AbstractStringBuffer::startsWith (const std::string_view & prefix) const nodiscard virtual noexcept
startsWith() [2/2]
bool sese::text::AbstractStringBuffer::startsWith (const std::string_view & text, const std::string_view & prefix) static noexcept
Referenced by sese::internal::service::http::HttpServiceImpl::handleFilter(), sese::internal::service::http::HttpServiceImpl::handleRequest(), and sese::text::StringBuffer::startsWith().
toSString()
String sese::text::AbstractStringBuffer::toSString () virtual
Reimplemented in sese::text::StringBuffer.
References buffer, and len.
Referenced by sese::text::StringBuffer::toSString().
toString()
std::string sese::text::AbstractStringBuffer::toString () virtual
Reimplemented in sese::text::StringBuffer.
References buffer, and len.
Referenced by sese::net::http::HPackUtil::buildCookieString(), sese::xml::XmlUtil::createElement(), sese::db::impl::PostgresDriverInstanceImpl::createStatement(), sese::PercentConverter::decode(), sese::SymbolConverter::decodeUnixClassName(), sese::net::dns::DnsPackage::decodeWords(), sese::record::SimpleFormatter::dump(), sese::PercentConverter::encode(), sese::net::dns::DnsPackage::encodeWords(), sese::net::dns::DnsPackage::Index::encodeWords(), sese::text::fmt(), sese::text::for_each(), sese::Yaml::getLine(), sese::net::http::RequestHeader::getUrl(), sese::RandomUtil::nextString(), sese::CSVReader::read(), sese::io::InputStreamReader::readLine(), sese::text::Number::toHex(), sese::text::Number::toHex(), sese::Json::tokenizer(), sese::xml::XmlUtil::tokenizer(), sese::Yaml::tokenizer(), sese::text::Number::toOct(), sese::text::Number::toOct(), sese::text::Number::toString(), sese::text::StringBuffer::toString(), and sese::Value::toString().
trim()
void sese::text::AbstractStringBuffer::trim () virtual noexcept
Remove whitespace at both ends.
Reimplemented in sese::text::StringBuffer.
References buffer, sese::isSpace(), and len.
Referenced by sese::text::StringBuffer::trim().
Member Data Documentation
buffer
char* sese::text::AbstractStringBuffer::buffer = nullptr protected
String length.
Referenced by buf(), del(), delCharAt(), getCharAt(), insertAt(), reverse(), setChatAt(), toSString(), toString(), trim(), and ~AbstractStringBuffer().
cap
size_t sese::text::AbstractStringBuffer::cap {} protected
Referenced by getCharAt(), insertAt(), setChatAt(), and size().
len
size_t sese::text::AbstractStringBuffer::len = 0 protected
Actual capacity.
Referenced by clear(), del(), delCharAt(), empty(), insertAt(), length(), reverse(), toSString(), toString(), and trim().
The documentation for this class was generated from the following files:
sese/text/AbstractStringBuffer.h
sese/text/AbstractStringBuffer.cpp