Sese Framework: sese::text Namespace Reference
sese::text Namespace Reference
Namespaces
namespace overload
Classes
class AbstractStringBuffer
String buffer class.
class DateTimeFormatter
Date time formatter class.
class DateTimeParser
Date parser.
struct FmtCtx
struct FormatOption
class Number
Number to String Utility.
class StringBuffer
Thread-safe string buffer class.
class StringBuilder
Non-thread-safe string buffer class.
class TextReader
Text reader class.
Typedefs
using Char = sstr::SChar
using String = sstr::SString
using StringView = sstr::SStringView
Enumerations
enum class Align { LEFT , CENTER , RIGHT }
Functions
bool FormatOption_StringParse (FormatOption &opt, const std::string &opt_str)
void FormatOption_StringFormat (FmtCtx &ctx, FormatOption &opt, const std::string &value)
bool FormatOption_NumberParse (FormatOption &opt, const std::string &opt_str)
template<typename T >
SESE_ALWAYS_INLINE void FormatOption_NumberFormatAlgin (FmtCtx &ctx, FormatOption &opt, T number, int radix, bool upper_case)
template<typename T >
void FormatOption_NumberFormat (FmtCtx &ctx, FormatOption &opt, T number)
template<typename T >
void FormatOption_FloatNumberFormat (FmtCtx &ctx, FormatOption &opt, T number)
template<typename C , std::enable_if_t<!is_pair< typename C::value_type >::value, int > = 0>
std::string for_each (const C &container)
constexpr size_t FormatParameterCounter (const char *pattern)
template<typename T >
void Format (FmtCtx &ctx, T &&arg)
template<typename T , typename... ARGS>
void Format (FmtCtx &ctx, T &&arg, ARGS &&...args)
template<typename... ARGS, std::enable_if_t< sizeof...(ARGS)==0, int > = 0>
std::string fmt (std::string_view pattern, ARGS &&...)
template<typename... ARGS, std::enable_if_t< sizeof...(ARGS) !=0, int > = 0>
std::string fmt (std::string_view pattern, ARGS &&...args)
int snprintf (char *buf, size_t buf_size, const char *pattern,...)
Typedef Documentation
Char
using sese::text::Char = sstr::SChar
String
using sese::text::String = sstr::SString
StringView
using sese::text::StringView = sstr::SStringView
Enumeration Type Documentation
Align
enum class sese::text::Align strong
Enumerator
LEFT
CENTER
RIGHT
Function Documentation
fmt() [1/2]
template<typename... ARGS, std::enable_if_t< sizeof...(ARGS)==0, int > = 0> std::string sese::text::fmt (std::string_view pattern, ARGS && ...)
String formatting
Template Parameters
ARGS Template parameters
Parameters
pattern Match pattern
Returns
Formatted string
References FormatParameterCounter().
fmt() [2/2]
template<typename... ARGS, std::enable_if_t< sizeof...(ARGS) !=0, int > = 0> std::string sese::text::fmt (std::string_view pattern, ARGS &&... args)
String formatting
Template Parameters
ARGS Template parameters
Parameters
pattern Match pattern
args Arguments
Returns
Formatted string
References sese::text::FmtCtx::builder, Format(), FormatParameterCounter(), and sese::text::AbstractStringBuffer::toString().
for_each()
template<typename C , std::enable_if_t<!is_pair< typename C::value_type >::value, int > = 0> std::string sese::text::for_each (const C & container)
References sese::text::FmtCtx::builder, and sese::text::AbstractStringBuffer::toString().
Format() [1/2]
template<typename T > void sese::text::Format (FmtCtx & ctx, T && arg)
References sese::text::FmtCtx::builder, sese::text::overload::Formatter< VALUE, ENABLE >::format(), and sese::text::FmtCtx::parsing().
Referenced by fmt(), and Format().
Format() [2/2]
template<typename T , typename... ARGS> void sese::text::Format (FmtCtx & ctx, T && arg, ARGS &&... args)
References sese::text::FmtCtx::builder, Format(), sese::text::overload::Formatter< VALUE, ENABLE >::format(), and sese::text::FmtCtx::parsing().
FormatOption_FloatNumberFormat()
template<typename T > void sese::text::FormatOption_FloatNumberFormat (FmtCtx & ctx, FormatOption & opt, T number)
Format string according to floating-point formatting standards
Template Parameters
T Floating-point type
Parameters
ctx Formatting context
opt Options
number Floating-point number
References sese::text::FormatOption::align, sese::text::AbstractStringBuffer::append(), sese::text::FmtCtx::builder, CENTER, sese::text::FormatOption::ext_type, sese::text::FormatOption::float_placeholder, sese::floating2StringLength(), LEFT, RIGHT, sese::text::Number::toString(), sese::text::FormatOption::wide, and sese::text::FormatOption::wide_char.
Referenced by sese::text::overload::Formatter< VALUE, std::enable_if_t< std::is_floating_point_v< VALUE > > >::format().
FormatOption_NumberFormat()
template<typename T > void sese::text::FormatOption_NumberFormat (FmtCtx & ctx, FormatOption & opt, T number)
Format string according to integer formatting standards, including alignment
Template Parameters
T Integer type
Parameters
ctx Formatting context
opt Options
number Integer
References sese::text::FormatOption::ext_type, and FormatOption_NumberFormatAlgin().
Referenced by sese::text::overload::Formatter< VALUE, std::enable_if_t< std::is_integral_v< VALUE > > >::format().
FormatOption_NumberFormatAlgin()
template<typename T > SESE_ALWAYS_INLINE void sese::text::FormatOption_NumberFormatAlgin (FmtCtx & ctx, FormatOption & opt, T number, int radix, bool upper_case)
References sese::text::FormatOption::align, sese::text::FmtCtx::builder, CENTER, LEFT, sese::number2StringLength(), RIGHT, sese::text::Number::toString(), sese::text::FormatOption::wide, and sese::text::FormatOption::wide_char.
Referenced by FormatOption_NumberFormat().
FormatOption_NumberParse()
bool sese::text::FormatOption_NumberParse (FormatOption & opt, const std::string & opt_str)
Parse and validate string formatting options
Parameters
opt Option
opt_str Option string
Returns
Whether the parsing was successful
References sese::text::FormatOption::ext_type, sese::text::FormatOption::float_placeholder, and sese::text::FormatOption::parse().
Referenced by sese::text::overload::Formatter< VALUE, std::enable_if_t< std::is_floating_point_v< VALUE > > >::parse(), and sese::text::overload::Formatter< VALUE, std::enable_if_t< std::is_integral_v< VALUE > > >::parse().
FormatOption_StringFormat()
void sese::text::FormatOption_StringFormat (FmtCtx & ctx, FormatOption & opt, const std::string & value)
Format string according to formatting options (alignment)
Parameters
ctx Context
opt Options
value String
References sese::text::FormatOption::align, sese::text::FmtCtx::builder, CENTER, LEFT, RIGHT, sese::text::FormatOption::wide, and sese::text::FormatOption::wide_char.
Referenced by sese::text::overload::Formatter< const char * >::format(), and sese::text::overload::Formatter< std::string >::format().
FormatOption_StringParse()
bool sese::text::FormatOption_StringParse (FormatOption & opt, const std::string & opt_str)
Parse and validate string formatting options
Parameters
opt Option
opt_str Option string
Returns
Whether the parsing was successful
References sese::text::FormatOption::ext_type, sese::text::FormatOption::float_placeholder, and sese::text::FormatOption::parse().
Referenced by sese::text::overload::Formatter< const char * >::parse(), and sese::text::overload::Formatter< std::string >::parse().
FormatParameterCounter()
size_t sese::text::FormatParameterCounter (const char * pattern) constexpr
References count().
Referenced by fmt(), and fmt().
snprintf()
int sese::text::snprintf (char * buf, size_t buf_size, const char * pattern, ...)
Cross-platform compatible snprintf
Parameters
buf Output buffer
buf_size Buffer size
pattern Format string
... Arguments for the format string
Returns
Result