Sese Framework: sese Namespace Reference
sese Namespace Reference
Namespaces
namespace _windows
namespace archive
namespace concurrent
namespace db
namespace event
namespace ini
namespace internal
namespace io
namespace iocp
namespace net
namespace plugin
namespace record
namespace res
namespace security
namespace service
namespace system
namespace text
namespace xml
Classes
class ArgParser
Command line argument parsing class.
class Base64Converter
BASE64 converter.
class Bimap
Bidirectional map.
struct Bitset32
Endian-independent 32-bit.
class BufferedQueue11
Cache queue (single producer-single consumer)
class BufferedQueueNn
Cache queue (multi producer-multi consumer)
class Compressor
Compressor class.
class ConfigObject
Traditional configuration file class.
class ConfigUtil
Traditional configuration file utility.
class CSVReader
CSV stream reader.
class CSVWriter
CSV stream writer.
class DateTime
Date time class.
class Decompressor
Decompressor class.
class EncodingConverter
String encoding conversion.
class EncodingConverterInitiateTask
Encoding converter initialization task.
class ErrorCode
Error code class.
class Exception
Exception class.
class GlobalThreadPool
Global thread pools, which use system thread pools on Windows, and slacker singleton thread pools on UNIX platforms.
class GZipFileInputStream
GZip file input stream (decompression)
class GZipFileOutputStream
GZip file output stream (compression)
struct has_begin
struct has_begin< T, void_t< decltype(std::declval< T >().begin())> >
struct has_end
struct has_end< T, void_t< decltype(std::declval< T >().begin())> >
class Initializer
Initializer.
class InitiateTask
Initialization task base class.
struct is_iterable
struct is_pair
struct is_pair< std::pair< T1, T2 > >
class Json
JSON parser.
class Locker
std::mutex wrapper
struct LongLongSplitter
Structure for data splitting.
class MD5Util
MD5 Algorithm Class.
class MemoryViewer
Memory viewer tool.
class MessageDigest
Message digest utility class.
class Noncopyable
Non-copyable class.
class NotInstantiable
Non-instantiable class.
class ObjectPool
Object pool.
class PercentConverter
Percent sign encoding converter.
class RandomUtil
Random utility class.
class Range
Range class.
class Result
Result Class.
class Result< T, E, std::enable_if_t< std::is_same_v< T, E > &&!std::is_void_v< T > &&!std::is_void_v< E > > >
class Result< T, E, std::enable_if_t<!std::is_same_v< T, E > &&!std::is_void_v< T > &&!std::is_void_v< E > > >
class Result< T, void >
class Result< void, E >
class Result< void, void >
class RingQueue
Ring queue.
struct SHA1Context
SHA1 context.
class SHA1Util
SHA1 algorithm tool.
class SHA256Util
SHA256 digest algorithm without hardware instruction acceleration, do not use this utility class if performance is a concern.
class Singleton
Raw Pointer Singleton Template Class.
class SingletonPtr
Smart Pointer Singleton Template Class.
class SpinLock
Spin Lock.
class StopWatch
Stopwatch Class.
struct StrCaseMapComparer
StrCaseMap Comparator.
struct StrCaseUnorderedMapComparer
StrCaseUnorderedMap Comparator.
struct StrCmp
Character comparator.
struct StrCmpI
Character comparator (case-insensitive)
class SymbolConverter
class Thread
Thread class.
class ThreadInitiateTask
Initialization task for the built-in thread class.
class ThreadPool
Thread pool class.
struct TimeoutEvent
Timeout Event.
struct TimeoutEventSlot
Timeout Event Slot (Time Wheel Slice)
class Timer
Low-Precision Timer Class.
class TimerTask
Timer Task.
class TimeSpan
Time Interval Class.
class TimestampHandler
Timestamp Handler.
class TimeWheel
Time Wheel.
class UniReader
Cross-platform file reader, primarily adapted for Windows, supports UTF-8.
class UnixException
Unix exception wrapper class.
class Uuid
Uuid Class.
class UuidBuilder
Uuid Builder.
class Value
Value Container Class.
class Version
Version Class.
class Yaml
YAML parser.
Typedefs
template<class T >
using BufferedQueueN1 = BufferedQueueNn<T>
Cache queue (multi producer-single consumer)
template<class T >
using BufferedQueue1N = BufferedQueueNn<T>
Cache queue (single producer-multi consumer)
template<typename VALUE , typename ALLOCATOR = std::allocator<std::pair<const std::string, VALUE>>>
using StrCaseMap = std::map<std::string, VALUE, StrCaseMapComparer, ALLOCATOR>
Dictionary class that ignores case of string keys.
template<typename VALUE , typename ALLOCATOR = std::allocator<std::pair<const std::string, VALUE>>>
using StrCaseUnorderedMap = std::unordered_map<std::string, VALUE, StrCaseUnorderedMapComparer, StrCaseUnorderedMapComparer, ALLOCATOR>
Dictionary class that ignores case of string keys.
using socket_t = int32_t
Native Socket type.
using tid_t = uint32_t
Thread ID identifier.
using pid_t = ::pid_t
Process ID identifier.
template<typename... >
using void_t = void
using NativeException = UnixException
template<typename T >
using SharedType = std::shared_ptr<T>
template<typename T >
using UniqueType = std::unique_ptr<T>
template<typename T >
using WeakType = std::weak_ptr<T>
Enumerations
enum class CompressionType { RAW = -30 , ZLIB = 0 , GZIP = 16 }
Functions
const char * getLevelString (record::Level level) noexcept
template<class RETURN_TYPE >
std::shared_future< RETURN_TYPE > async (const std::function< RETURN_TYPE()> &task) noexcept
Launch an anonymous thread to execute a task.
template<class RETURN_TYPE >
std::shared_future< RETURN_TYPE > async (ThreadPool &pool, const std::function< RETURN_TYPE()> &task) noexcept
Submit a task to an existing thread pool.
template<class RETURN_TYPE >
std::shared_future< RETURN_TYPE > asyncWithGlobalPool (const std::function< RETURN_TYPE()> &task) noexcept
Submit a task to the global thread pool.
void initCore (int argc, const char *const *argv) noexcept
Initialize sese-core.
template<typename RETURN_TYPE , typename... ARGS>
SharedType< RETURN_TYPE > makeShared (ARGS &&...args)
template<typename RETURN_TYPE , typename... ARGS>
SharedType< RETURN_TYPE > makeUnique (ARGS &&...args)
template<typename RETURN_TYPE , typename INIT_TYPE >
SharedType< RETURN_TYPE > makeSharedFromList (std::initializer_list< INIT_TYPE > list)
template<typename RETURN_TYPE , typename INIT_TYPE >
UniqueType< RETURN_TYPE > makeUniqueFromList (std::initializer_list< INIT_TYPE > list)
template<typename RETURN_TYPE , typename RAW_TYPE >
SharedType< RETURN_TYPE > dynamicPointerCast (SharedType< RAW_TYPE > raw_type)
template<typename RETURN_TYPE , typename RAW_TYPE >
UniqueType< RETURN_TYPE > dynamicPointerCast (UniqueType< RAW_TYPE > &raw_type)
int64_t toInteger (const std::string &string, int radix=10)
std::string getClassName (const std::type_info *type)
bool strcmp (char const *lv, char const *rv) noexcept
bool strcmpDoNotCase (char const *lv, char const *rv) noexcept
bool isSpace (char ch) noexcept
const char * getLevelString (Level level) noexcept
int32_t findFirstAt (const char *str, char ch)
void sleep (uint32_t second)
template<class REP , class PERIOD >
void sleep (const std::chrono::duration< REP, PERIOD > &duration)
std::string getErrorString (int64_t error=errno)
int32_t getErrorCode ()
size_t streamMove (sese::io::OutputStream *out, sese::io::InputStream *in, size_t size) noexcept
template<class T >
size_t number2StringLength (T num, size_t radix=10)
template<class T >
size_t floating2StringLength (T num, uint16_t placeholder)
template<typename TP >
std::time_t to_time_t (TP tp)
template<typename T >
bool isAdditionOverflow (T a, T b)
Additive spill detection.
template<typename T >
bool isSubtractionOverflow (T a, T b)
Subtractive spill detection.
Variables
thread_local std::shared_ptr< sese::Thread::RuntimeData > current_data = nullptr
template<typename T >
constexpr bool is_iterable_v = is_iterable<T>::value
Typedef Documentation
BufferedQueue1N
template<class T > using sese::BufferedQueue1N = BufferedQueueNn<T>
Cache queue (single producer-multi consumer)
BufferedQueueN1
template<class T > using sese::BufferedQueueN1 = BufferedQueueNn<T>
Cache queue (multi producer-single consumer)
NativeException
using sese::NativeException = UnixException
pid_t
typedef DWORD sese::pid_t = ::pid_t
Process ID identifier.
SharedType
template<typename T > using sese::SharedType = std::shared_ptr<T>
socket_t
typedef SOCKET sese::socket_t = int32_t
Native Socket type.
StrCaseMap
template<typename VALUE , typename ALLOCATOR = std::allocator<std::pair<const std::string, VALUE>>> using sese::StrCaseMap = std::map<std::string, VALUE, StrCaseMapComparer, ALLOCATOR>
Dictionary class that ignores case of string keys.
Template Parameters
VALUE Dictionary value type
ALLOCATOR Memory allocator
StrCaseUnorderedMap
template<typename VALUE , typename ALLOCATOR = std::allocator<std::pair<const std::string, VALUE>>> using sese::StrCaseUnorderedMap = std::unordered_map<std::string, VALUE, StrCaseUnorderedMapComparer, StrCaseUnorderedMapComparer, ALLOCATOR>
Dictionary class that ignores case of string keys.
Template Parameters
VALUE Dictionary value type
ALLOCATOR Memory allocator
tid_t
typedef uint32_t sese::tid_t = uint32_t
Thread ID identifier.
UniqueType
template<typename T > using sese::UniqueType = std::unique_ptr<T>
void_t
template<typename... > using sese::void_t = void
WeakType
template<typename T > using sese::WeakType = std::weak_ptr<T>
Enumeration Type Documentation
CompressionType
enum class sese::CompressionType strong
Enumerator
RAW
ZLIB
GZIP
Function Documentation
async() [1/2]
template<class RETURN_TYPE > std::shared_future< RETURN_TYPE > sese::async (const std::function< RETURN_TYPE()> & task) noexcept
Launch an anonymous thread to execute a task.
Template Parameters
RETURN_TYPE Return type
Parameters
task Task
Returns
std::shared_future object
async() [2/2]
template<class RETURN_TYPE > std::shared_future< RETURN_TYPE > sese::async (ThreadPool & pool, const std::function< RETURN_TYPE()> & task) noexcept
Submit a task to an existing thread pool.
Template Parameters
RETURN_TYPE Return type
Parameters
pool Existing thread pool
task Task
Returns
std::shared_future object
References sese::ThreadPool::postTask().
asyncWithGlobalPool()
template<class RETURN_TYPE > std::shared_future< RETURN_TYPE > sese::asyncWithGlobalPool (const std::function< RETURN_TYPE()> & task) noexcept
Submit a task to the global thread pool.
Template Parameters
RETURN_TYPE Return type
Parameters
task Task
Returns
std::shared_future object
References sese::GlobalThreadPool::postTask().
dynamicPointerCast() [1/2]
template<typename RETURN_TYPE , typename RAW_TYPE > SharedType< RETURN_TYPE > sese::dynamicPointerCast (SharedType< RAW_TYPE > raw_type) inline
Type casting for std::shared_ptr
Template Parameters
RETURN_TYPE Template parameter expected to return std::shared_ptr
RAW_TYPE Template parameter of the original std::shared_ptr
Parameters
raw_type std::shared_ptr to convert
Returns
std::shared_ptr<ReturnType>
dynamicPointerCast() [2/2]
template<typename RETURN_TYPE , typename RAW_TYPE > UniqueType< RETURN_TYPE > sese::dynamicPointerCast (UniqueType< RAW_TYPE > & raw_type)
Type casting for std::unique_ptr
Template Parameters
RETURN_TYPE Template parameter expected to return std::unique_ptr
RAW_TYPE Template parameter of the original std::unique_ptr
Parameters
raw_type std::unique_ptr to convert
Returns
std::unique_ptr<ReturnType>
findFirstAt()
int32_t sese::findFirstAt (const char * str, char ch)
Find the first occurrence of a character in a string
Parameters
str The string to search in
ch The character to find
Returns
The position of the first occurrence, or -1 if not found
References at().
floating2StringLength()
template<class T > size_t sese::floating2StringLength (T num, uint16_t placeholder)
Get the byte length required to convert a number to a string
Note
Only floating-point numbers can be converted
Template Parameters
T Input floating-point number type
Parameters
num Number to be converted
placeholder Precision
Returns
Length required for the number string
References number2StringLength().
Referenced by sese::text::FormatOption_FloatNumberFormat(), and sese::text::Number::toString().
getClassName()
std::string sese::getClassName (const std::type_info * type)
Get the name of the class
Parameters
type Class
Returns
Name of the class
getErrorCode()
int32_t sese::getErrorCode ()
Retrieve error code
Returns
Error code
Referenced by sese::io::FileStream::createEx(), sese::system::IPCChannel::createEx(), sese::system::Process::createEx(), sese::system::SharedMemory::createEx(), sese::plugin::Module::openEx(), sese::system::IPCChannel::useEx(), and sese::system::SharedMemory::useEx().
getErrorString()
std::string sese::getErrorString (int64_t error = errno)
Retrieve error message
Parameters
error Error code
Returns
Error description
Referenced by sese::io::FileStream::createEx(), sese::system::IPCChannel::createEx(), sese::system::Process::createEx(), sese::system::SharedMemory::createEx(), sese::net::getNetworkErrorString(), sese::plugin::Module::openEx(), sese::system::IPCChannel::useEx(), and sese::system::SharedMemory::useEx().
getLevelString() [1/2]
const char * sese::getLevelString (Level level) noexcept
Return corresponding string based on log level
Parameters
level Log level
Returns
String
getLevelString() [2/2]
const char * sese::getLevelString (record::Level level) noexcept
References sese::record::DEBUG, sese::record::ERR, sese::record::INFO, and sese::record::WARN.
Referenced by sese::record::SimpleFormatter::dump().
initCore()
void sese::initCore (int argc, const char *const * argv) noexcept
Initialize sese-core.
Parameters
argc Number of arguments
argv Array of arguments
References sese::Initializer::addTask().
isAdditionOverflow()
template<typename T > bool sese::isAdditionOverflow (T a, T b)
Additive spill detection.
References a, and b.
Referenced by sese::internal::service::http::HttpConnectionEx::handleWindowUpdate().
isSpace()
bool sese::isSpace (char ch) noexcept
Determine if a character is a whitespace
Parameters
ch Character to be checked
Returns
Whether it is a whitespace
References SPACE_CHARS.
Referenced by sese::Json::tokenizer(), sese::xml::XmlUtil::tokenizer(), and sese::text::AbstractStringBuffer::trim().
isSubtractionOverflow()
template<typename T > bool sese::isSubtractionOverflow (T a, T b)
Subtractive spill detection.
References a, and b.
makeShared()
template<typename RETURN_TYPE , typename... ARGS> SharedType< RETURN_TYPE > sese::makeShared (ARGS &&... args) inline
Instantiate SharedType
Template Parameters
RETURN_TYPE Template parameter for SharedType
ARGS Constructor parameter types for the template parameter
Parameters
args Constructor parameters for the template parameter
Returns
SharedType<ReturnType>
makeSharedFromList()
template<typename RETURN_TYPE , typename INIT_TYPE > SharedType< RETURN_TYPE > sese::makeSharedFromList (std::initializer_list< INIT_TYPE > list)
Using std::make_shared with std::initializer_list
Template Parameters
RETURN_TYPE Template type expected to return std::shared_ptr
INIT_TYPE Template parameter for std::initializer_list
Parameters
list Initialization list
Returns
std::shared_ptr<ReturnType>
makeUnique()
template<typename RETURN_TYPE , typename... ARGS> SharedType< RETURN_TYPE > sese::makeUnique (ARGS &&... args) inline
Instantiate UniqueType
Template Parameters
RETURN_TYPE Template parameter for UniqueType
ARGS Constructor parameter types for the template parameter
Parameters
args Constructor parameters for the template parameter
Returns
Unique
makeUniqueFromList()
template<typename RETURN_TYPE , typename INIT_TYPE > UniqueType< RETURN_TYPE > sese::makeUniqueFromList (std::initializer_list< INIT_TYPE > list)
Using std::make_unique with std::initializer_list
Template Parameters
RETURN_TYPE Template parameter expected to return std::unique_ptr
INIT_TYPE Template parameter for std::initializer_list
Parameters
list Initialization list
Returns
std::unique_ptr<ReturnType>
number2StringLength()
template<class T > size_t sese::number2StringLength (T num, size_t radix = 10)
Get the byte length required to convert a number to a string
Note
Only integers can be converted
Template Parameters
T Input integer type
Parameters
num Number to be converted
radix Base
Returns
Length required for the number string
Referenced by floating2StringLength(), sese::text::FormatOption_NumberFormatAlgin(), sese::text::Number::toHex(), sese::text::Number::toHex(), sese::text::Number::toOct(), sese::text::Number::toOct(), sese::text::Number::toString(), and sese::net::http::Range::toStringLength().
sleep() [1/2]
template<class REP , class PERIOD > void sese::sleep (const std::chrono::duration< REP, PERIOD > & duration)
Make the current thread sleep for a while, implemented using std::this_thread::sleep_for
Parameters
duration The duration to sleep
sleep() [2/2]
void sese::sleep (uint32_t second)
Make the current thread sleep for a while, implemented using NATIVE API
Parameters
second Seconds
References sleep().
Referenced by sese::net::Socket::connect(), sese::security::SecuritySocket::connect(), sese::Timer::loop(), sese::internal::service::http::HttpServiceImpl::shutdown(), and sleep().
strcmp()
bool sese::strcmp (char const * lv, char const * rv) noexcept
Compare two strings for equality
Parameters
lv String 1
rv String 2
Returns
Comparison result
Referenced by sese::net::ws::WebsocketAuthenticator::verify().
strcmpDoNotCase()
bool sese::strcmpDoNotCase (char const * lv, char const * rv) noexcept
Compare two strings for equality (case-insensitive)
Parameters
lv String 1
rv String 2
Returns
Comparison result
References strcmpi.
Referenced by sese::net::http::HttpConverter::convertFromHttp2(), sese::net::http::RequestableFactory::createHttpRequest(), sese::net::http::HPackUtil::decode(), sese::db::impl::SqlitePreparedStatementImpl::getColumnType(), sese::internal::service::http::HttpServiceImpl::handleRequest(), in(), sese::Yaml::parseBasic(), and sese::internal::net::http::HttpClientImpl::request().
streamMove()
size_t sese::streamMove (sese::io::OutputStream * out, sese::io::InputStream * in, size_t size) noexcept
Move stream data
Parameters
out Output stream
in Input stream
size Size to move
Returns
Actual size moved
References in().
Referenced by sese::internal::service::http::HttpConnection::readBody(), and sese::internal::service::http::HttpConnection::readHeader().
to_time_t()
template<typename TP > std::time_t sese::to_time_t (TP tp)
Time type conversion
See also
https://stackoverflow.com/questions/61030383/how-to-convert-stdfilesystemfile-time-type-to-time-t
Template Parameters
TP Type of the object to convert
Parameters
tp Object to convert
Returns
Time in std::time_t type
Referenced by sese::internal::service::http::HttpServiceImpl::handleRequest().
toInteger()
int64_t sese::toInteger (const std::string & string, int radix = 10)
Integer conversion function that ignores errors
Parameters
string String representing the integer
radix Base
Returns
Integer
Referenced by sese::internal::service::http::HttpConnectionEx::handleDataFrame(), and sese::internal::service::http::HttpConnection::readHeader().
Variable Documentation
current_data
thread_local std::shared_ptr<sese::Thread::RuntimeData> sese::current_data = nullptr
Referenced by sese::Thread::getCurrentThreadData(), sese::Thread::getCurrentThreadId(), sese::Thread::getCurrentThreadName(), and sese::Thread::run().
is_iterable_v
template<typename T > bool sese::is_iterable_v = is_iterable<T>::value constexpr