Sese Framework: sese::internal::net Namespace Reference
sese::internal::net Namespace Reference
Namespaces
namespace service
Functions
asio::ip::address convert (const sese::net::IPAddress::Ptr &addr)
template<typename EndpointType >
sese::net::IPAddress::Ptr convert (const EndpointType &endpoint)
asio::ssl::context convert (std::unique_ptr< security::SSLContext > context)
Function Documentation
convert() [1/3]
template<typename EndpointType > sese::net::IPAddress::Ptr sese::internal::net::convert (const EndpointType & endpoint)
convert() [2/3]
asio::ip::address sese::internal::net::convert (const sese::net::IPAddress::Ptr & addr) inline
Referenced by sese::internal::net::service::dns::DnsService::bind(), sese::internal::net::service::dns::DnsService::handle(), sese::internal::service::http::HttpsConnectionImpl::HttpsConnectionImpl(), sese::net::http::HttpClient::Impl::request(), sese::net::dns::Resolver::resolve(), and sese::internal::service::http::HttpServiceImpl::startup().
convert() [3/3]
asio::ssl::context sese::internal::net::convert (std::unique_ptr< security::SSLContext > context) inline
Calling this function will transfer ownership of the context to the new converted object, and the old object will no longer be valid
Parameters
context The context
Returns
New asio context object