Sese Framework: sese::IOBufNode Struct Reference
sese::IOBufNode Struct Reference
IOBuf Node.
#include <IOBuf.h>
Public Member Functions
IOBufNode (size_t capacity)
~IOBufNode ()
size_t getReadableSize () const noexcept
size_t getWriteableSize () const noexcept
Public Attributes
void * buffer {nullptr}
Cache pointers.
size_t read {0}
Cache read size.
size_t size {0}
The cache is populated with size.
const size_t CAPACITY
The size of the cache capacity.
Detailed Description
IOBuf Node.
Constructor & Destructor Documentation
IOBufNode()
sese::IOBufNode::IOBufNode (size_t capacity) explicit
Creates a new node
Parameters
capacity The size of the node's capacity
References buffer.
~IOBufNode()
sese::IOBufNode::~IOBufNode ()
References free().
Member Function Documentation
getReadableSize()
size_t sese::IOBufNode::getReadableSize () const nodiscard noexcept
Get the readable size of the node
Returns
Readable size
References read().
Referenced by sese::IOBuf::peek().
getWriteableSize()
size_t sese::IOBufNode::getWriteableSize () const nodiscard noexcept
Get the writable size of the node
Returns
Writable size (free portion)
Member Data Documentation
buffer
void* sese::IOBufNode::buffer {nullptr}
Cache pointers.
Referenced by IOBufNode(), and sese::IOBuf::peek().
CAPACITY
const size_t sese::IOBufNode::CAPACITY
The size of the cache capacity.
read
size_t sese::IOBufNode::read {0}
Cache read size.
Referenced by sese::IOBuf::peek().
size
size_t sese::IOBufNode::size {0}
The cache is populated with size.
Referenced by sese::IOBuf::peek().
The documentation for this struct was generated from the following files:
sese/util/IOBuf.h
sese/util/IOBuf.cpp