name: Bug Feedback
description: 此模板用于报告不符合预期的问题
labels: ["bug"]
assignees:
  - SHIINASAMA
  - DreamerQcl
title: "[bug]: "
body:
  - type: markdown
    attributes:
      value: |
        在描述你的问题之前请先尝试自己解决或者查找相似的 issue。
  - type: checkboxes
    id: checklist
    attributes:
      label: 确认清单
      options:
        - label: 我已尝试自己去解决这个问题，但不在我的能力或者职责范围之内。
          required: true
  - type: textarea
    id: description
    attributes:
      label: 问题描述
  - type: input
    id: platform
    attributes:
      label: 平台
      description: 请输入程序所运行的平台
    validations:
      required: true
  - type: dropdown
    id: module-type
    attributes:
      label: 模块
      description: 请选择需要报告的模块
      options:
        - common
        - archive
        - db interface
        - sqlite
        - mariadb
        - mysql
        - postgres
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 程序版本
      description: 请输入你使用的程序版本
    validations:
      required: true
