FROM ubuntu:latest

ENV TERM=xterm-256color

RUN export DEBIAN_FRONTEND=noninteractive && \
    bash -c 'yes | unminimize'

RUN apt-get update -y && \
    apt-get install -y git gcc g++ cmake ninja-build clangd python3 libgtest-dev libssl-dev zlib1g-dev